// client/src/components/library/DiscoveredAudiobooks.tsx
import { useState, useEffect } from "react";
import { Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  Search,
  Scan,
  CheckSquare,
  Square,
  FolderInput,
  Loader2,
  FileAudio,
  CheckCircle2,
  AlertTriangle,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { OperationProgressBar } from "@/components/OperationProgressBar";
import { BookEditForm } from "@/components/BookEditForm";
import { libraryApi, audiobookApi } from "@/services/api";
import { useSignalREvent, useSignalRReconnected } from "@/hooks/useSignalR";
import { handleApiError } from "@/lib/api";
import { splitList } from "@/helpers/organizeAudiobookInput";
import { toast } from "sonner";
import type { DiscoveredAudiobook } from "@/types/DiscoveredAudiobook";
import type { Audiobook } from "@/types/Audiobook";

interface ScanProgressPayload {
  message: string;
  filesScanned: number;
  totalFiles: number;
}

interface ScanCompletePayload {
  totalFilesScanned: number;
  newFilesDiscovered: number;
  alreadyTracked: number;
}

interface ImportProgressPayload {
  processed: number;
  total: number;
  succeeded: number;
  failed: number;
}

interface ImportCompletePayload {
  totalProcessed: number;
  totalSucceeded: number;
  totalFailed: number;
}

interface OrganizeProgressPayload {
  originalFileLocation: string;
  progress: number;
  progressMessage: string;
}

interface OrganizeQueueErrorPayload {
  originalFileLocation: string;
  error: string;
}

export function DiscoveredAudiobooks() {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [page, setPage] = useState(1);
  const [pageSize] = useState(25);
  const [selectedPaths, setSelectedPaths] = useState<Set<string>>(new Set());

  // Live organize progress/error for the per-item "Import to Library" action, keyed by the
  // discovered file's path (same key the backend reports UpdateProgress/QueueError under).
  const [organizeOverrides, setOrganizeOverrides] = useState<
    Record<string, { progress?: number; message?: string; error?: string }>
  >({});

  // Scan state
  const [scanning, setScanning] = useState(false);
  const [scanProgress, setScanProgress] = useState<{
    message: string;
    scanned: number;
    total: number;
  } | null>(null);
  const [scanResult, setScanResult] = useState<ScanCompletePayload | null>(null);

  // Bulk import state
  const [importing, setImporting] = useState(false);
  const [importProgress, setImportProgress] = useState<{
    processed: number;
    total: number;
    succeeded: number;
    failed: number;
  } | null>(null);

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(search);
      setPage(1);
    }, 300);
    return () => clearTimeout(timer);
  }, [search]);

  const { data, isLoading: loading } = useQuery({
    queryKey: ["discoveredAudiobooks", debouncedSearch, page, pageSize],
    queryFn: () =>
      libraryApi.getDiscovered(
        pageSize,
        (page - 1) * pageSize,
        debouncedSearch.trim() || undefined,
      ),
  });

  const books: DiscoveredAudiobook[] = data?.items ?? [];
  const totalCount = data?.total ?? 0;

  // SignalR scan events
  useSignalREvent<ScanProgressPayload>("LibraryScanProgress", (data) => {
    setScanning(true);
    setScanProgress({
      message: data.message,
      scanned: data.filesScanned,
      total: data.totalFiles,
    });
  });

  useSignalREvent<ScanCompletePayload>("LibraryScanComplete", (data) => {
    setScanning(false);
    setScanProgress(null);
    setScanResult(data);
    toast.success(
      `Scan complete: ${data.newFilesDiscovered} new files, ${data.alreadyTracked} already tracked`,
    );
    void queryClient.invalidateQueries({
      queryKey: ["discoveredAudiobooks"],
    });
  });

  // SignalR import events
  useSignalREvent<ImportProgressPayload>("DiscoveredImportProgress", (data) => {
    setImporting(true);
    setImportProgress(data);
  });

  useSignalREvent<ImportCompletePayload>("DiscoveredImportComplete", (data) => {
    setImporting(false);
    setImportProgress(null);
    setSelectedPaths(new Set());
    toast.success(`Import complete: ${data.totalSucceeded} succeeded, ${data.totalFailed} failed`);
    void queryClient.invalidateQueries({
      queryKey: ["discoveredAudiobooks"],
    });
  });

  // SignalR single-item organize events (queued via "Import to Library" below)
  useSignalREvent<OrganizeProgressPayload>("UpdateProgress", (payload) => {
    setOrganizeOverrides((prev) => ({
      ...prev,
      [payload.originalFileLocation]: {
        progress: payload.progress,
        message: payload.progressMessage,
      },
    }));

    if (payload.progress >= 100) {
      void queryClient.invalidateQueries({
        queryKey: ["discoveredAudiobooks"],
      });
    }
  });

  useSignalREvent<OrganizeQueueErrorPayload>("QueueError", (payload) => {
    setOrganizeOverrides((prev) => ({
      ...prev,
      [payload.originalFileLocation]: {
        error: payload.error,
      },
    }));
    toast.error(`Organize failed: ${payload.error}`);
  });

  // A dropped/re-established connection may have missed progress or completion events for
  // an in-flight import; re-fetching re-derives the list's state the same way it does on mount.
  useSignalRReconnected(() => {
    void queryClient.invalidateQueries({
      queryKey: ["discoveredAudiobooks"],
    });
  });

  const handleStartScan = async () => {
    setScanning(true);
    setScanResult(null);
    try {
      await libraryApi.startScan();
      toast.success("Library scan started in background");
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
      setScanning(false);
    }
  };

  const handleToggleSelectPath = (path: string) => {
    setSelectedPaths((prev) => {
      const next = new Set(prev);
      if (next.has(path)) next.delete(path);
      else next.add(path);
      return next;
    });
  };

  const wellTaggedEligible = books.filter((b) => b.isWellTagged && !b.isDuplicate);

  const handleSelectAllWellTagged = () => {
    if (selectedPaths.size === wellTaggedEligible.length) {
      setSelectedPaths(new Set());
    } else {
      setSelectedPaths(new Set(wellTaggedEligible.map((b) => b.fullPath)));
    }
  };

  const handleBulkImport = async () => {
    if (selectedPaths.size === 0) return;
    setImporting(true);
    try {
      await libraryApi.bulkImport(Array.from(selectedPaths));
      toast.success(`Import queued for ${selectedPaths.size} books`);
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
      setImporting(false);
    }
  };

  const handleDeleteDiscovered = async (path: string) => {
    try {
      await libraryApi.deleteDiscovered(path);
      toast.success("File record removed");
      void queryClient.invalidateQueries({
        queryKey: ["discoveredAudiobooks"],
      });
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    }
  };

  const handleOrganizeDiscovered = async (path: string, book: Audiobook) => {
    try {
      await audiobookApi.organizeBook(book);
      toast.success("Book added to organization queue");
      setOrganizeOverrides((prev) => ({
        ...prev,
        [path]: { progress: 0, message: "Queued..." },
      }));
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    }
  };

  const totalPages = Math.ceil(totalCount / pageSize) || 1;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <Button variant="ghost" size="sm" render={<Link to="/library" />}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Library
        </Button>

        <Button
          variant="default"
          onClick={() => {
            void handleStartScan();
          }}
          disabled={scanning}
        >
          <Scan className={`mr-2 h-4 w-4 ${scanning ? "animate-spin" : ""}`} />
          {scanning ? "Scanning Library..." : "Scan Library"}
        </Button>
      </div>

      <div>
        <h1 className="text-foreground text-2xl font-bold">Discovered Audiobooks ({totalCount})</h1>
        <p className="text-muted-foreground text-sm">
          Audiobook files found in the library directory that are not yet tracked in the database.
          Books marked "Well tagged" have valid tags and can be bulk imported.
        </p>
      </div>

      {scanning && scanProgress && (
        <OperationProgressBar
          processed={scanProgress.scanned}
          total={scanProgress.total}
          label={scanProgress.message}
        />
      )}

      {scanResult && (
        <div className="border-primary/20 bg-primary/10 text-foreground rounded-lg border p-3 text-xs">
          Scan complete: {scanResult.newFilesDiscovered} new files discovered,{" "}
          {scanResult.alreadyTracked} already tracked.
        </div>
      )}

      {importing && importProgress && (
        <OperationProgressBar
          processed={importProgress.processed}
          total={importProgress.total}
          label={`Importing audiobooks (${importProgress.succeeded} succeeded, ${importProgress.failed} failed)`}
        />
      )}

      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="relative max-w-md flex-1">
          <Search className="text-muted-foreground absolute top-2.5 left-3 h-4 w-4" />
          <Input
            placeholder="Filter by filename..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>

        {wellTaggedEligible.length > 0 && (
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handleSelectAllWellTagged}>
              {selectedPaths.size === wellTaggedEligible.length ? (
                <CheckSquare className="mr-1.5 h-4 w-4" />
              ) : (
                <Square className="mr-1.5 h-4 w-4" />
              )}
              Select all well-tagged ({wellTaggedEligible.length})
            </Button>

            {selectedPaths.size > 0 && (
              <Button
                size="sm"
                disabled={importing}
                onClick={() => {
                  void handleBulkImport();
                }}
              >
                <FolderInput className="mr-1.5 h-4 w-4" />
                Import Selected ({selectedPaths.size})
              </Button>
            )}
          </div>
        )}
      </div>

      {loading && books.length === 0 ? (
        <div className="text-muted-foreground flex flex-col items-center justify-center py-16">
          <Loader2 className="text-primary mb-3 h-8 w-8 animate-spin" />
          <p className="text-sm">Loading discovered files...</p>
        </div>
      ) : books.length === 0 ? (
        <Card className="p-12 text-center">
          <FileAudio className="text-muted-foreground/40 mx-auto mb-3 h-12 w-12" />
          <h3 className="text-foreground text-lg font-medium">No discovered files</h3>
          <p className="text-muted-foreground mt-1 text-sm">
            Click "Scan Library" to search your library folder for untracked files.
          </p>
        </Card>
      ) : (
        <Accordion type="single" collapsible className="space-y-2">
          {books.map((book) => {
            const isSelected = selectedPaths.has(book.fullPath);
            const override = organizeOverrides[book.fullPath];
            const isOrganizing = Boolean(override && override.error == null);
            const organizeError = override?.error;

            const initialAudiobook: Audiobook = {
              authors: splitList(book.authors).map((name) => ({ name })),
              narrators: splitList(book.narrators).map((name) => ({ name })),
              bookName: book.bookName,
              subtitle: book.subtitle,
              series: book.series,
              seriesPart: book.seriesPart,
              year: book.year,
              genres: splitList(book.genres),
              fileInfo: {
                fullPath: book.fullPath,
                fileName: book.fileName,
                sizeInBytes: book.sizeInBytes,
              },
            };

            return (
              <AccordionItem
                key={book.fullPath}
                value={book.fullPath}
                className="border-border bg-card rounded-lg border px-4 shadow-sm"
              >
                <AccordionTrigger className="py-3 hover:no-underline">
                  <div className="flex w-full flex-wrap items-center justify-between gap-3 pr-4 text-left">
                    <div className="flex min-w-0 items-center gap-3">
                      {book.isWellTagged && !book.isDuplicate && (
                        <input
                          type="checkbox"
                          checked={isSelected}
                          onChange={(e) => {
                            e.stopPropagation();
                            handleToggleSelectPath(book.fullPath);
                          }}
                          onClick={(e) => e.stopPropagation()}
                          className="border-border h-4 w-4 rounded"
                        />
                      )}
                      <div className="min-w-0 truncate">
                        <div className="text-foreground truncate font-semibold">
                          {book.authors ? `${book.authors} — ` : ""}
                          {book.bookName || book.fileName}
                        </div>
                        <div className="text-muted-foreground truncate text-xs">
                          {book.fileName}
                        </div>
                      </div>
                    </div>

                    <div className="flex shrink-0 items-center gap-2">
                      {book.isWellTagged ? (
                        <Badge
                          variant="secondary"
                          className="gap-1 bg-emerald-500/15 text-[11px] text-emerald-600 dark:text-emerald-400"
                        >
                          <CheckCircle2 className="h-3 w-3" />
                          Well tagged
                        </Badge>
                      ) : null}

                      {book.isDuplicate ? (
                        <Badge variant="destructive" className="gap-1 text-[11px]">
                          <AlertTriangle className="h-3 w-3" />
                          Duplicate target
                        </Badge>
                      ) : null}

                      {isOrganizing && (
                        <div className="w-36 text-right">
                          {override?.progress != null ? (
                            <OperationProgressBar
                              processed={override.progress}
                              total={100}
                              label={override.message || "Organizing..."}
                            />
                          ) : (
                            <span className="text-muted-foreground text-xs">
                              {override?.message || "Queued..."}
                            </span>
                          )}
                        </div>
                      )}

                      {organizeError && (
                        <Badge variant="destructive" className="gap-1 text-[11px]">
                          <AlertTriangle className="h-3 w-3" />
                          Organize failed
                        </Badge>
                      )}
                    </div>
                  </div>
                </AccordionTrigger>

                <AccordionContent className="border-border border-t pt-4 pb-4">
                  <div className="space-y-4">
                    <div className="flex justify-end gap-2">
                      <Button
                        variant="destructive"
                        size="sm"
                        onClick={() => {
                          void handleDeleteDiscovered(book.fullPath);
                        }}
                      >
                        <Trash2 className="mr-1.5 h-3.5 w-3.5" />
                        Dismiss / Delete
                      </Button>
                    </div>

                    <BookEditForm
                      initialBook={initialAudiobook}
                      currentPath={book.fullPath}
                      onSave={(edited) => handleOrganizeDiscovered(book.fullPath, edited)}
                      formActions={
                        <Button type="submit">
                          <FolderInput className="mr-2 h-4 w-4" />
                          Import to Library
                        </Button>
                      }
                    />
                  </div>
                </AccordionContent>
              </AccordionItem>
            );
          })}
        </Accordion>
      )}

      {totalPages > 1 && (
        <div className="flex items-center justify-between pt-2">
          <span className="text-muted-foreground text-xs">
            Page {page} of {totalPages} ({totalCount} total)
          </span>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              disabled={page <= 1 || loading}
              onClick={() => setPage((p) => Math.max(1, p - 1))}
            >
              Previous
            </Button>
            <Button
              variant="outline"
              size="sm"
              disabled={page >= totalPages || loading}
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
            >
              Next
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

export default DiscoveredAudiobooks;

// client/src/components/library/DiscoveredAudiobooks.vue
<template>
  <v-container>
    <v-row class="text-center">
      <v-col class="mb-5">
        <h2 class="headline font-weight-bold mb-5">Discovered Audiobooks</h2>
      </v-col>
    </v-row>
    <v-row>
      <v-col cols="12">
        <v-btn
          class="mr-3"
          to="/library"
          prepend-icon="mdi-arrow-left"
        >
          Back to Library
        </v-btn>
        <v-btn
          :disabled="scanning"
          :loading="scanning"
          @click="startScan()"
        >
          Scan Library
        </v-btn>
        <div class="text-caption text-medium-emphasis mt-1">
          Scans the library directory for audiobook files that aren't yet
          tracked in the database.
        </div>
        <template v-if="scanning">
          <OperationProgressBar
            class="mt-3"
            :processed="scanFilesScanned"
            :total="scanTotalFiles"
          />
          <div class="text-caption mt-1">{{ scanMessage }}</div>
        </template>
        <v-alert
          v-if="scanComplete"
          type="info"
          class="mt-3"
          closable
          @click:close="scanComplete = false"
        >
          Scan complete: {{ scanNewFiles }} new files discovered,
          {{ scanTrackedFiles }} already tracked.
        </v-alert>
      </v-col>
    </v-row>
    <v-row>
      <v-col cols="12">
        <p class="text-body-2 text-medium-emphasis mb-3">
          Audiobook files found in the library directory that aren't yet tracked
          in the database. Books with a
          <v-chip
            size="x-small"
            color="success"
            class="mx-1"
            >Well tagged</v-chip
          >
          badge already have author, book name, and year and can be added in
          bulk. Expand a book to review its full metadata and add it
          individually.
        </p>
        <v-text-field
          v-model="discoveredSearchQuery"
          label="Filter by filename"
          prepend-inner-icon="mdi-magnify"
          clearable
          hide-details
          density="compact"
          class="mb-3"
        />
        <div
          v-if="discoveredBooks.length"
          class="d-flex align-center justify-space-between mb-2 flex-wrap ga-2"
        >
          <div class="d-flex align-center">
            <v-checkbox
              :model-value="isAllWellTaggedSelected"
              :indeterminate="isSomeWellTaggedSelected"
              :disabled="wellTaggedBooks.length === 0"
              density="compact"
              hide-details
              label="Select all well-tagged"
              @update:model-value="toggleSelectAllWellTagged()"
            />
            <span
              v-if="selectedPaths.size > 0"
              class="text-caption text-medium-emphasis ml-2"
            >
              {{ selectedPaths.size }} selected
            </span>
          </div>
          <v-btn
            v-if="selectedPaths.size > 0"
            size="small"
            variant="outlined"
            color="primary"
            :loading="importing"
            :disabled="importing"
            @click="onImportSelectedClick()"
          >
            Import Selected ({{ selectedPaths.size }})
          </v-btn>
        </div>
        <template v-if="importing">
          <OperationProgressBar
            class="mb-3"
            :processed="importProcessed"
            :total="importTotal"
          />
        </template>
        <v-expansion-panels
          v-if="discoveredBooks.length"
          v-model="discoveredActivePanel"
        >
          <v-expansion-panel
            v-for="(book, i) in discoveredBooks"
            :key="i"
          >
            <v-expansion-panel-title>
              <v-row align="center">
                <v-col cols="auto">
                  <v-checkbox
                    :model-value="selectedPaths.has(book.fullPath)"
                    density="compact"
                    hide-details
                    @click.stop
                    @update:model-value="toggleBookSelected(book)"
                  />
                </v-col>
                <v-col>
                  {{ book.fileName }}
                  <v-chip
                    v-if="book.isWellTagged"
                    size="x-small"
                    color="success"
                    class="ml-2"
                  >
                    Well tagged
                  </v-chip>
                </v-col>
                <v-col>
                  <template v-if="book.error">
                    <span class="text-red">{{ book.error }}</span>
                    <v-icon>mdi-alert</v-icon>
                  </template>
                  <template v-else-if="book.queueId">
                    {{ book.queueMessage ?? "Queued" }}
                    <v-progress-circular
                      :model-value="book.queueProgress ?? 0"
                      size="23"
                      :width="2"
                    />
                  </template>
                </v-col>
                <v-col>
                  {{ formatFileSize(book.sizeInBytes) }}
                </v-col>
              </v-row>
            </v-expansion-panel-title>
            <v-expansion-panel-text>
              <BookOrganize
                :book-path="book.fullPath"
                @book-queued="(id) => markDiscoveredAsQueued(book, id)"
                @book-deleted="() => removeDiscoveredBook(book)"
              />
            </v-expansion-panel-text>
          </v-expansion-panel>
        </v-expansion-panels>
        <div
          v-else
          class="text-center mt-2"
        >
          No discovered audiobooks
        </div>
        <v-pagination
          v-model="discoveredCurrentPage"
          :length="discoveredTotalPages"
        ></v-pagination>
      </v-col>
    </v-row>

    <v-dialog
      v-model="importConfirmDialog"
      max-width="500"
    >
      <v-card>
        <v-card-title>Confirm Import</v-card-title>
        <v-card-text>
          This will add <strong>{{ selectedPaths.size }}</strong> book{{
            selectedPaths.size === 1 ? "" : "s"
          }}
          to the library using the tags already read from each file, moving each
          file into place in the process.
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="importConfirmDialog = false">Cancel</v-btn>
          <v-btn
            color="primary"
            @click="confirmImportSelected()"
          >
            Import
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-snackbar
      v-model="snackbar"
      :timeout="4000"
    >
      {{ snackbarText }}
    </v-snackbar>
  </v-container>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, Ref, ref, watch } from "vue";
import { debounce } from "lodash";
import BookOrganize from "../BookOrganize.vue";
import OperationProgressBar from "../OperationProgressBar.vue";
import LibraryService from "../../services/LibraryService";
import DiscoveredAudiobook from "../../types/DiscoveredAudiobook";
import { useSignalR, HubEventToken } from "@/signalr/hub";
import { useOperationProgress } from "../../composables/useOperationProgress";
import { LibraryScanProgress } from "../../signalr/LibraryScanProgress";
import { LibraryScanComplete } from "../../signalr/LibraryScanComplete";
import { ProgressUpdate } from "../../signalr/ProgressUpdate";
import { QueueError } from "../../signalr/QueueError";
import { DiscoveredImportProgress } from "../../signalr/DiscoveredImportProgress";
import { DiscoveredImportComplete } from "../../signalr/DiscoveredImportComplete";

const LibraryScanProgressToken: HubEventToken<LibraryScanProgress> =
  "LibraryScanProgress";
const LibraryScanCompleteToken: HubEventToken<LibraryScanComplete> =
  "LibraryScanComplete";
const UpdateProgress: HubEventToken<ProgressUpdate> = "UpdateProgress";
const QueueErrorToken: HubEventToken<QueueError> = "QueueError";
const DiscoveredImportProgressToken: HubEventToken<DiscoveredImportProgress> =
  "DiscoveredImportProgress";
const DiscoveredImportCompleteToken: HubEventToken<DiscoveredImportComplete> =
  "DiscoveredImportComplete";

const signalR = useSignalR();

const limit = 50;

const discoveredBooks: Ref<DiscoveredAudiobook[]> = ref([]);
const discoveredSearchQuery: Ref<string> = ref("");
const discoveredActivePanel: Ref<any> = ref(null);
const discoveredCurrentPage: Ref<number> = ref(1);
const discoveredTotalItems: Ref<number> = ref(0);

const selectedPaths: Ref<Set<string>> = ref(new Set());
const importConfirmDialog: Ref<boolean> = ref(false);
const snackbar: Ref<boolean> = ref(false);
const snackbarText: Ref<string> = ref("");

const scanMessage: Ref<string> = ref("");
const scanComplete: Ref<boolean> = ref(false);
const scanNewFiles: Ref<number> = ref(0);
const scanTrackedFiles: Ref<number> = ref(0);

const {
  isRunning: scanning,
  processed: scanFilesScanned,
  total: scanTotalFiles,
  start: startScanning,
} = useOperationProgress<LibraryScanProgress, LibraryScanComplete>({
  key: "library-scan",
  progressToken: LibraryScanProgressToken,
  completeToken: LibraryScanCompleteToken,
  getProcessed: (arg) => arg.filesScanned,
  getTotal: (arg) => arg.totalFiles,
  onProgress: (arg) => {
    scanMessage.value = arg.message;
  },
  onComplete: (arg) => {
    scanComplete.value = true;
    scanNewFiles.value = arg.newFilesDiscovered;
    scanTrackedFiles.value = arg.alreadyTracked;
    loadDiscoveredBooks();
  },
});

const {
  isRunning: importing,
  processed: importProcessed,
  total: importTotal,
  start: startImporting,
} = useOperationProgress<DiscoveredImportProgress, DiscoveredImportComplete>({
  key: "discovered-import",
  progressToken: DiscoveredImportProgressToken,
  completeToken: DiscoveredImportCompleteToken,
  getProcessed: (arg) => arg.processed,
  getTotal: (arg) => arg.total,
  onComplete: (arg) => {
    let msg = `Import complete: ${arg.totalSucceeded} of ${arg.totalProcessed} books added`;
    if (arg.totalFailed > 0) {
      msg += ` (${arg.totalFailed} failed)`;
    }
    snackbarText.value = msg;
    snackbar.value = true;
    selectedPaths.value = new Set();
    loadDiscoveredBooks();
  },
});

const onUpdateProgress = (arg: ProgressUpdate) => {
  const book = discoveredBooks.value.find(
    (x) => x.queueId === arg.originalFileLocation,
  );
  if (book) {
    book.queueMessage = arg.progressMessage;
    book.queueProgress = arg.progress;
  }
};

const onQueueError = (arg: QueueError) => {
  const book = discoveredBooks.value.find(
    (x) => x.queueId === arg.originalFileLocation,
  );
  if (book) {
    book.error = arg.error;
  }
};

signalR.on(UpdateProgress, onUpdateProgress);
signalR.on(QueueErrorToken, onQueueError);

onUnmounted(() => {
  signalR.off(UpdateProgress, onUpdateProgress);
  signalR.off(QueueErrorToken, onQueueError);
  signalR.offReconnected(loadDiscoveredBooks);
});

const discoveredTotalPages = computed((): number =>
  Math.ceil(discoveredTotalItems.value / limit),
);

const wellTaggedBooks = computed((): DiscoveredAudiobook[] =>
  discoveredBooks.value.filter((b) => b.isWellTagged),
);

const isAllWellTaggedSelected = computed(
  (): boolean =>
    wellTaggedBooks.value.length > 0 &&
    wellTaggedBooks.value.every((b) => selectedPaths.value.has(b.fullPath)),
);

const isSomeWellTaggedSelected = computed(
  (): boolean =>
    !isAllWellTaggedSelected.value &&
    wellTaggedBooks.value.some((b) => selectedPaths.value.has(b.fullPath)),
);

const toggleSelectAllWellTagged = () => {
  if (isAllWellTaggedSelected.value) {
    for (const book of wellTaggedBooks.value) {
      selectedPaths.value.delete(book.fullPath);
    }
  } else {
    for (const book of wellTaggedBooks.value) {
      selectedPaths.value.add(book.fullPath);
    }
  }
  selectedPaths.value = new Set(selectedPaths.value);
};

const toggleBookSelected = (book: DiscoveredAudiobook) => {
  if (selectedPaths.value.has(book.fullPath)) {
    selectedPaths.value.delete(book.fullPath);
  } else {
    selectedPaths.value.add(book.fullPath);
  }
  selectedPaths.value = new Set(selectedPaths.value);
};

const onImportSelectedClick = () => {
  importConfirmDialog.value = true;
};

const confirmImportSelected = async () => {
  importConfirmDialog.value = false;
  startImporting();
  try {
    await LibraryService.bulkImportDiscovered(Array.from(selectedPaths.value));
  } catch (e: any) {
    importing.value = false;
    snackbarText.value = `Failed to start import: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  }
};

watch(discoveredCurrentPage, () => {
  loadDiscoveredBooks();
});

const startScan = async () => {
  startScanning();
  scanComplete.value = false;
  scanMessage.value = "";
  await LibraryService.startLibraryScan();
};

const loadDiscoveredBooks = async () => {
  const result = await LibraryService.getDiscoveredBooks(
    limit,
    (discoveredCurrentPage.value - 1) * limit,
    discoveredSearchQuery.value || undefined,
  );
  discoveredTotalItems.value = result.total;
  discoveredBooks.value = result.items;
};

// A queued book's UpdateProgress/QueueError events can be missed while disconnected (e.g. a
// backgrounded mobile tab), leaving it stuck showing "Queued" even after it finished. Reloading
// the list on reconnect re-syncs queue state the same way it does on mount.
signalR.onReconnected(loadDiscoveredBooks);

const debouncedDiscoveredSearch = debounce(() => {
  discoveredCurrentPage.value = 1;
  loadDiscoveredBooks();
}, 300);

watch(discoveredSearchQuery, () => {
  debouncedDiscoveredSearch();
});

const markDiscoveredAsQueued = async (
  book: DiscoveredAudiobook,
  queueId: string,
) => {
  book.queueId = queueId;
  var bookIdx = discoveredBooks.value.indexOf(book);
  if (bookIdx === discoveredActivePanel.value) {
    discoveredActivePanel.value = null;
  }
  selectedPaths.value.delete(book.fullPath);
  selectedPaths.value = new Set(selectedPaths.value);
  await LibraryService.deleteDiscoveredBook(book.fullPath);
};

const removeDiscoveredBook = (book: DiscoveredAudiobook) => {
  var bookIdx = discoveredBooks.value.indexOf(book);
  var currentlyOpen = bookIdx === discoveredActivePanel.value;

  discoveredBooks.value = discoveredBooks.value.filter((b) => b != book);
  selectedPaths.value.delete(book.fullPath);
  selectedPaths.value = new Set(selectedPaths.value);

  if (currentlyOpen) {
    discoveredActivePanel.value = null;
  }
};

const formatFileSize = (size: number) => {
  const sizeInMb = size / 1000000;
  return `${sizeInMb.toFixed(1)} MB`;
};

onMounted(() => {
  loadDiscoveredBooks();
});
</script>
