// client/src/components/library/SeriesMatchDialog.tsx
import { useState } from "react";
import { Search, Loader2 } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { OperationProgressBar } from "@/components/OperationProgressBar";
import { seriesApi } from "@/services/api";
import { useSignalREvent } from "@/hooks/useSignalR";
import { handleApiError } from "@/lib/api";
import { toast } from "sonner";
import type { SeriesMatchCandidate, SeriesOverview } from "@/types/Series";

interface SeriesMatchProgressPayload {
  processed: number;
  total: number;
  succeeded: number;
  failed: number;
}

interface SeriesMatchCompletePayload {
  totalProcessed: number;
  totalSucceeded: number;
  totalFailed: number;
  stopReason?: string;
}

interface SeriesMatchDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  series: SeriesOverview[];
  onMatched?: () => void;
}

export function SeriesMatchDialog({
  open,
  onOpenChange,
  series,
  onMatched,
}: SeriesMatchDialogProps) {
  const [threshold, setThreshold] = useState(0.85);
  const [selected, setSelected] = useState<string[]>([]);
  const [suggestions, setSuggestions] = useState<Record<string, SeriesMatchCandidate | null>>({});
  const [loadingSuggestions, setLoadingSuggestions] = useState(false);

  const [matching, setMatching] = useState(false);
  const [matchProgress, setMatchProgress] = useState<SeriesMatchProgressPayload | null>(null);

  const [prevOpen, setPrevOpen] = useState(open);
  if (open !== prevOpen) {
    setPrevOpen(open);
    if (open) {
      setSelected(series.map((s) => s.name));
      setSuggestions({});
    }
  }

  useSignalREvent<SeriesMatchProgressPayload>("SeriesMatchProgress", (payload) => {
    setMatching(true);
    setMatchProgress(payload);
  });

  useSignalREvent<SeriesMatchCompletePayload>("SeriesMatchComplete", (payload) => {
    setMatching(false);
    setMatchProgress(null);
    const msg = payload.stopReason
      ? `Matching stopped after ${payload.totalProcessed} series: ${payload.stopReason}`
      : `Matching complete: ${payload.totalSucceeded} of ${payload.totalProcessed} series matched${
          payload.totalFailed > 0 ? ` (${payload.totalFailed} failed)` : ""
        }`;
    toast.success(msg);
    onMatched?.();
  });

  const allSelected = series.length > 0 && selected.length === series.length;

  const toggleAll = () => {
    setSelected(allSelected ? [] : series.map((s) => s.name));
  };

  const toggleOne = (name: string) => {
    setSelected((prev) => (prev.includes(name) ? prev.filter((n) => n !== name) : [...prev, name]));
  };

  const handleLoadSuggestions = async () => {
    setLoadingSuggestions(true);
    try {
      for (const item of series) {
        try {
          const candidates = await seriesApi.getMatchCandidates(item.name);
          setSuggestions((prev) => ({
            ...prev,
            [item.name]: candidates[0] ?? null,
          }));
        } catch {
          setSuggestions((prev) => ({ ...prev, [item.name]: null }));
        }
      }
    } finally {
      setLoadingSuggestions(false);
    }
  };

  const handleStartMatch = async () => {
    if (selected.length === 0) return;
    setMatching(true);
    try {
      await seriesApi.startBulkMatch(threshold, selected);
      toast.success("Bulk series matching started in background");
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
      setMatching(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="flex max-h-[85vh] max-w-2xl flex-col overflow-hidden">
        <DialogHeader>
          <DialogTitle>Bulk Match Series</DialogTitle>
        </DialogHeader>

        <div className="flex-1 space-y-4 overflow-y-auto py-2 text-xs">
          <p className="text-muted-foreground">
            Each unmatched series is looked up at every metadata source that supports series
            lookups. Only series whose best candidate scores at or above the threshold are matched;
            the rest are skipped.
          </p>

          <div className="border-border bg-muted/40 space-y-3 rounded-lg border p-4">
            <div className="flex items-center justify-between">
              <span className="font-semibold">Confidence Threshold</span>
              <span className="font-mono font-medium">{Math.round(threshold * 100)}%</span>
            </div>
            <input
              type="range"
              value={threshold}
              min={0.5}
              max={1.0}
              step={0.01}
              onChange={(e) => setThreshold(parseFloat(e.target.value))}
              disabled={matching}
              className="accent-primary bg-muted h-2 w-full cursor-pointer rounded-lg"
            />
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={loadingSuggestions || matching || series.length === 0}
                onClick={() => {
                  void handleLoadSuggestions();
                }}
              >
                {loadingSuggestions ? (
                  <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Search className="mr-1.5 h-3.5 w-3.5" />
                )}
                Preview Suggestions
              </Button>
              <Button variant="ghost" size="sm" disabled={matching} onClick={toggleAll}>
                {allSelected ? "Deselect All" : "Select All"}
              </Button>
            </div>
            <span className="text-muted-foreground">
              {selected.length} of {series.length} selected
            </span>
          </div>

          {matching && matchProgress && (
            <OperationProgressBar
              processed={matchProgress.processed}
              total={matchProgress.total}
              label={`Matching series (${matchProgress.succeeded} succeeded, ${matchProgress.failed} failed)`}
            />
          )}

          {series.length === 0 ? (
            <div className="text-muted-foreground py-6 text-center">
              Every series is already matched.
            </div>
          ) : (
            <div className="border-border divide-y rounded-md border">
              {series.map((item) => {
                const isSelected = selected.includes(item.name);
                const best = suggestions[item.name];
                return (
                  <div
                    key={item.name}
                    className="hover:bg-muted/50 flex items-start gap-3 p-2.5 transition-colors"
                  >
                    <Checkbox
                      checked={isSelected}
                      disabled={matching}
                      onCheckedChange={() => toggleOne(item.name)}
                      className="mt-0.5"
                    />
                    <div className="min-w-0 flex-1">
                      <div className="text-foreground font-medium">{item.name}</div>
                      <div className="text-muted-foreground flex flex-wrap items-center gap-1.5 text-[11px]">
                        <span>{(item.authors ?? []).join(", ") || "Unknown author"}</span>
                        <span>&middot;</span>
                        <span>{item.ownedBookCount} owned</span>
                        {best !== undefined && (
                          <>
                            <span>&middot;</span>
                            {best === null ? (
                              <span className="italic">no candidates found</span>
                            ) : (
                              <span className="flex items-center gap-1">
                                best: <strong>{best.seriesName}</strong> ({best.sourceName},{" "}
                                {Math.round(best.confidence * 100)}%)
                                {best.confidence < threshold && (
                                  <Badge variant="secondary" className="px-1 text-[10px]">
                                    below threshold
                                  </Badge>
                                )}
                              </span>
                            )}
                          </>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        <div className="border-border flex justify-end gap-2 border-t pt-4">
          <Button variant="outline" disabled={matching} onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button
            disabled={matching || selected.length === 0}
            onClick={() => {
              void handleStartMatch();
            }}
          >
            {matching ? (
              <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />
            ) : (
              <Search className="mr-1.5 h-4 w-4" />
            )}
            Match Selected ({selected.length})
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default SeriesMatchDialog;

// client/src/components/library/SeriesMatchDialog.vue
<template>
  <v-dialog
    :model-value="modelValue"
    max-width="900"
    scrollable
    @update:model-value="$emit('update:modelValue', $event)"
  >
    <v-card>
      <v-card-title>Bulk match series</v-card-title>
      <v-card-subtitle class="text-wrap">
        Each unmatched series is looked up at every metadata source that
        supports series lookups. Only series whose best candidate scores at or
        above the threshold are matched; the rest are skipped.
      </v-card-subtitle>

      <v-card-text>
        <v-row>
          <v-col
            cols="12"
            md="6"
          >
            <v-slider
              v-model="threshold"
              label="Confidence threshold"
              :min="0.5"
              :max="1"
              :step="0.01"
              hide-details
              thumb-label
            >
              <template v-slot:append>
                <span class="text-body-2">
                  {{ Math.round(threshold * 100) }}%
                </span>
              </template>
            </v-slider>
          </v-col>
          <v-col
            cols="12"
            md="6"
            class="d-flex align-center ga-2"
          >
            <v-btn
              :disabled="loadingSuggestions || matching || series.length === 0"
              :loading="loadingSuggestions"
              prepend-icon="mdi-magnify"
              @click="loadSuggestions()"
            >
              Preview suggestions
            </v-btn>
            <v-btn
              variant="text"
              :disabled="matching"
              @click="toggleAll()"
            >
              {{ allSelected ? "Deselect all" : "Select all" }}
            </v-btn>
          </v-col>
        </v-row>

        <v-progress-linear
          v-if="matching"
          class="my-3"
          :model-value="total > 0 ? (processed / total) * 100 : 0"
          color="primary"
          height="20"
          striped
        >
          <template v-slot:default> {{ processed }} / {{ total }} </template>
        </v-progress-linear>
        <div
          v-if="matching"
          class="text-caption mb-2"
        >
          Succeeded: {{ succeeded }}, Failed: {{ failed }}
        </div>

        <div
          v-if="series.length === 0"
          class="text-caption text-medium-emphasis"
        >
          Every series is already matched.
        </div>

        <v-list v-else>
          <v-list-item
            v-for="item in series"
            :key="item.name"
          >
            <template v-slot:prepend>
              <v-checkbox-btn
                :model-value="selected.includes(item.name)"
                :disabled="matching"
                @update:model-value="toggle(item.name)"
              />
            </template>
            <v-list-item-title>{{ item.name }}</v-list-item-title>
            <v-list-item-subtitle>
              <span>{{ item.authors.join(", ") || "Unknown author" }}</span>
              <span> &middot; {{ item.ownedBookCount }} owned</span>
              <template v-if="suggestions[item.name] !== undefined">
                <span v-if="suggestions[item.name] === null">
                  &middot; no candidates found
                </span>
                <span v-else>
                  &middot; best:
                  <strong>{{ suggestions[item.name]!.seriesName }}</strong>
                  ({{ suggestions[item.name]!.sourceName }},
                  {{ Math.round(suggestions[item.name]!.confidence * 100) }}%)
                  <v-chip
                    v-if="suggestions[item.name]!.confidence < threshold"
                    size="x-small"
                    class="ml-1"
                  >
                    below threshold
                  </v-chip>
                </span>
              </template>
            </v-list-item-subtitle>
          </v-list-item>
        </v-list>
      </v-card-text>

      <v-card-actions>
        <v-spacer />
        <v-btn
          :disabled="matching"
          @click="close()"
        >
          Close
        </v-btn>
        <v-btn
          color="primary"
          :disabled="matching || selected.length === 0"
          @click="startMatch()"
        >
          Match selected ({{ selected.length }})
        </v-btn>
      </v-card-actions>
    </v-card>

    <v-snackbar
      v-model="snackbar"
      :timeout="4000"
    >
      {{ snackbarText }}
    </v-snackbar>
  </v-dialog>
</template>

<script setup lang="ts">
import { computed, onUnmounted, Ref, ref, watch } from "vue";
import SeriesService from "../../services/SeriesService";
import { SeriesMatchCandidate, SeriesOverview } from "../../types/Series";
import { HubEventToken, useSignalR } from "@/signalr/hub";
import { SeriesMatchProgress } from "../../signalr/SeriesMatchProgress";
import { SeriesMatchComplete } from "../../signalr/SeriesMatchComplete";

const props = defineProps<{
  modelValue: boolean;
  series: SeriesOverview[];
}>();

const emit = defineEmits<{
  (e: "update:modelValue", value: boolean): void;
  (e: "matched"): void;
}>();

const SeriesMatchProgressToken: HubEventToken<SeriesMatchProgress> =
  "SeriesMatchProgress";
const SeriesMatchCompleteToken: HubEventToken<SeriesMatchComplete> =
  "SeriesMatchComplete";

const signalR = useSignalR();

const threshold = ref(0.85);
const selected: Ref<string[]> = ref([]);
// null means "looked up, nothing found" - distinct from "not looked up yet" (undefined).
const suggestions: Ref<Record<string, SeriesMatchCandidate | null>> = ref({});
const loadingSuggestions = ref(false);

const matching = ref(false);
const processed = ref(0);
const total = ref(0);
const succeeded = ref(0);
const failed = ref(0);

const snackbar = ref(false);
const snackbarText = ref("");

const allSelected = computed(
  () =>
    props.series.length > 0 && selected.value.length === props.series.length,
);

watch(
  () => props.modelValue,
  (open) => {
    if (open) {
      selected.value = props.series.map((s) => s.name);
    }
  },
);

const toggle = (name: string) => {
  selected.value = selected.value.includes(name)
    ? selected.value.filter((n) => n !== name)
    : [...selected.value, name];
};

const toggleAll = () => {
  selected.value = allSelected.value ? [] : props.series.map((s) => s.name);
};

const loadSuggestions = async () => {
  loadingSuggestions.value = true;
  try {
    // Sequential on purpose: each lookup hits an external metadata API.
    for (const item of props.series) {
      try {
        const candidates = await SeriesService.getMatchCandidates(item.name);
        suggestions.value = {
          ...suggestions.value,
          [item.name]: candidates.length > 0 ? candidates[0] : null,
        };
      } catch {
        suggestions.value = { ...suggestions.value, [item.name]: null };
      }
    }
  } finally {
    loadingSuggestions.value = false;
  }
};

const startMatch = async () => {
  matching.value = true;
  processed.value = 0;
  total.value = 0;
  succeeded.value = 0;
  failed.value = 0;

  try {
    await SeriesService.startBulkMatch(threshold.value, selected.value);
  } catch (e: any) {
    matching.value = false;
    snackbarText.value = `Failed to start matching: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  }
};

const close = () => emit("update:modelValue", false);

const onMatchProgress = (arg: SeriesMatchProgress) => {
  processed.value = arg.processed;
  total.value = arg.total;
  succeeded.value = arg.succeeded;
  failed.value = arg.failed;
};

const onMatchComplete = (arg: SeriesMatchComplete) => {
  matching.value = false;
  let msg = arg.stopReason
    ? `Matching stopped after ${arg.totalProcessed} series: ${arg.stopReason}`
    : `Matching complete: ${arg.totalSucceeded} of ${arg.totalProcessed} series matched`;
  if (arg.totalFailed > 0) {
    msg += ` (${arg.totalFailed} failed)`;
  }
  snackbarText.value = msg;
  snackbar.value = true;
  emit("matched");
};

signalR.on(SeriesMatchProgressToken, onMatchProgress);
signalR.on(SeriesMatchCompleteToken, onMatchComplete);

onUnmounted(() => {
  signalR.off(SeriesMatchProgressToken, onMatchProgress);
  signalR.off(SeriesMatchCompleteToken, onMatchComplete);
});
</script>
