// client/src/components/library/SeriesDetail.vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <v-btn
          variant="text"
          prepend-icon="mdi-arrow-left"
          @click="goBack"
        >
          Back
        </v-btn>
      </v-col>
    </v-row>
    <v-row>
      <v-col>
        <h2 class="text-h5">{{ seriesName }}</h2>
        <div class="text-subtitle-1">
          {{ books.length }} {{ books.length === 1 ? "book" : "books" }} owned
          <span v-if="overview?.isMatched && overview.missingBookCount > 0">
            &middot; {{ overview.missingBookCount }} missing
          </span>
        </div>
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12">
        <v-card variant="outlined">
          <v-card-text>
            <div class="d-flex align-center flex-wrap ga-2">
              <template v-if="overview?.isMatched">
                <v-chip
                  size="small"
                  color="success"
                  variant="tonal"
                >
                  Matched to {{ overview.matchedSourceName }}
                </v-chip>
                <a
                  v-if="overview.matchedSourceUrl"
                  :href="overview.matchedSourceUrl"
                  target="_blank"
                  rel="noopener"
                  class="text-caption"
                >
                  View at source
                </a>
                <span
                  v-if="overview.matchConfidence != null"
                  class="text-caption text-medium-emphasis"
                >
                  Confidence
                  {{ Math.round(overview.matchConfidence * 100) }}%
                </span>
                <span
                  v-if="overview.lastRefreshedAt"
                  class="text-caption text-medium-emphasis"
                >
                  Last refreshed
                  {{ new Date(overview.lastRefreshedAt).toLocaleString() }}
                </span>
              </template>
              <v-chip
                v-else
                size="small"
                variant="tonal"
              >
                Not matched to a metadata source
              </v-chip>

              <v-spacer />

              <v-btn
                size="small"
                :disabled="busy"
                :loading="loadingCandidates"
                prepend-icon="mdi-link-variant"
                @click="loadCandidates()"
              >
                {{
                  overview?.isMatched ? "Re-match to source" : "Match to source"
                }}
              </v-btn>
              <v-btn
                v-if="overview?.isMatched"
                size="small"
                :disabled="busy"
                prepend-icon="mdi-cloud-refresh"
                @click="refreshSeries()"
              >
                Refresh metadata
              </v-btn>
            </div>

            <v-checkbox
              v-model="includeOmnibusEditions"
              label="Include omnibus/box-set editions"
              hint="When off, bundles like a 'Books 1-4' omnibus are left out of the missing-books list."
              persistent-hint
              density="compact"
              hide-details="auto"
              class="mt-2"
              :disabled="busy || updatingOmnibusSetting"
              @update:model-value="onIncludeOmnibusEditionsChanged"
            />

            <div class="d-flex align-center flex-wrap ga-2 mt-3">
              <v-text-field
                v-model="manualQuery"
                label="Search title/author, or paste a series URL"
                hint="e.g. https://hardcover.app/series/harry-potter"
                density="compact"
                variant="outlined"
                hide-details
                clearable
                style="min-width: 280px; flex: 1 1 280px"
                :disabled="busy"
                @keydown.enter="searchManualCandidates()"
              />
              <v-btn
                size="small"
                :disabled="busy || !manualQuery?.trim()"
                :loading="searchingManually"
                prepend-icon="mdi-magnify"
                @click="searchManualCandidates()"
              >
                Search
              </v-btn>
            </div>

            <v-progress-linear
              v-if="refreshing"
              class="mt-3"
              :model-value="
                refreshTotal > 0 ? (refreshProcessed / refreshTotal) * 100 : 0
              "
              color="primary"
              height="20"
              striped
            >
              <template v-slot:default>
                {{ refreshProcessed }} / {{ refreshTotal }}
              </template>
            </v-progress-linear>

            <div
              v-if="candidates.length"
              class="mt-4"
            >
              <div class="text-subtitle-2 mb-2">Candidates</div>
              <v-list density="compact">
                <v-list-item
                  v-for="candidate in candidates"
                  :key="`${candidate.sourceName}-${candidate.sourceId}`"
                >
                  <v-list-item-title>
                    {{ candidate.seriesName }}
                    <v-chip
                      size="x-small"
                      class="ml-2"
                    >
                      {{ Math.round(candidate.confidence * 100) }}%
                    </v-chip>
                  </v-list-item-title>
                  <v-list-item-subtitle>
                    {{ candidate.sourceName }}
                    <span v-if="candidate.authors.length">
                      &middot; {{ candidate.authors.join(", ") }}
                    </span>
                    <span v-if="candidate.bookCount != null">
                      &middot; {{ candidate.bookCount }} books
                    </span>
                  </v-list-item-subtitle>
                  <template v-slot:append>
                    <v-btn
                      size="small"
                      color="primary"
                      :disabled="busy"
                      @click="applyMatch(candidate)"
                    >
                      Use
                    </v-btn>
                  </template>
                </v-list-item>
              </v-list>
            </div>
            <div
              v-else-if="candidatesLoaded"
              class="text-caption text-medium-emphasis mt-3"
            >
              No candidates found. A source that supports series lookups
              (currently Hardcover) must be configured with an API key.
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <v-row>
      <v-col>
        <h3 class="text-h6 mb-2">Owned books</h3>
        <v-list v-if="books.length">
          <v-list-item
            v-for="book in books"
            :key="book.id"
            :to="`/library/book/${book.id}`"
          >
            <v-list-item-title>
              <span v-if="book.seriesPart"
                >Part {{ book.seriesPart }} &mdash;
              </span>
              {{ book.bookName }}
            </v-list-item-title>
            <v-list-item-subtitle>
              <span v-if="book.authors.length">{{
                book.authors.join(", ")
              }}</span>
              <span v-if="book.year"> &middot; {{ book.year }}</span>
              <span v-if="book.narrators.length">
                &middot; Narrated by {{ book.narrators.join(", ") }}
              </span>
              <span v-if="book.durationInSeconds">
                &middot; {{ formatDuration(book.durationInSeconds) }}
              </span>
            </v-list-item-subtitle>
            <template v-slot:append>
              <v-icon>mdi-chevron-right</v-icon>
            </template>
          </v-list-item>
        </v-list>
        <div
          v-else-if="loading"
          class="text-center"
        >
          <v-progress-circular indeterminate />
        </div>
        <div
          v-else
          class="text-center"
        >
          No books found in this series
        </div>
      </v-col>
    </v-row>

    <v-row v-if="missingBooks.length">
      <v-col>
        <h3 class="text-h6 mb-2">Missing books ({{ missingBooks.length }})</h3>
        <v-list>
          <v-list-item
            v-for="book in missingBooks"
            :key="book.id"
          >
            <v-list-item-title>
              <span v-if="book.position"
                >Part {{ book.position }} &mdash;
              </span>
              {{ book.title }}
            </v-list-item-title>
            <v-list-item-subtitle>
              <span v-if="book.year">{{ book.year }}</span>
              <a
                v-if="book.sourceUrl"
                :href="book.sourceUrl"
                target="_blank"
                rel="noopener"
                class="ml-2"
              >
                View at source
              </a>
            </v-list-item-subtitle>
            <template v-slot:append>
              <v-btn
                size="small"
                variant="text"
                :disabled="busy"
                @click="setIgnored(book, true)"
              >
                Ignore
              </v-btn>
            </template>
          </v-list-item>
        </v-list>
      </v-col>
    </v-row>

    <v-row v-if="ignoredBooks.length">
      <v-col>
        <div class="d-flex align-center mb-2">
          <v-btn
            icon
            variant="text"
            density="comfortable"
            :aria-label="
              ignoredCollapsed
                ? 'Expand ignored books'
                : 'Collapse ignored books'
            "
            @click="ignoredCollapsed = !ignoredCollapsed"
          >
            <v-icon>{{
              ignoredCollapsed ? "mdi-chevron-right" : "mdi-chevron-down"
            }}</v-icon>
          </v-btn>
          <h3 class="text-h6">Ignored books ({{ ignoredBooks.length }})</h3>
        </div>
        <v-list v-show="!ignoredCollapsed">
          <v-list-item
            v-for="book in ignoredBooks"
            :key="book.id"
          >
            <v-list-item-title class="text-medium-emphasis">
              <span v-if="book.position"
                >Part {{ book.position }} &mdash;
              </span>
              {{ book.title }}
            </v-list-item-title>
            <template v-slot:append>
              <v-btn
                size="small"
                variant="text"
                :disabled="busy"
                @click="setIgnored(book, false)"
              >
                Unignore
              </v-btn>
            </template>
          </v-list-item>
        </v-list>
      </v-col>
    </v-row>

    <v-snackbar
      v-model="snackbar"
      :timeout="4000"
    >
      {{ snackbarText }}
    </v-snackbar>
  </v-container>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, Ref, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import SeriesService from "../../services/SeriesService";
import { formatDuration } from "../../helpers/formatHelpers";
import {
  SeriesExpectedBook,
  SeriesMatchCandidate,
  SeriesOverview,
  SeriesOwnedBook,
} from "../../types/Series";
import { HubEventToken, useSignalR } from "@/signalr/hub";
import { SeriesRefreshProgress } from "../../signalr/SeriesRefreshProgress";
import { SeriesRefreshComplete } from "../../signalr/SeriesRefreshComplete";

const SeriesRefreshProgressToken: HubEventToken<SeriesRefreshProgress> =
  "SeriesRefreshProgress";
const SeriesRefreshCompleteToken: HubEventToken<SeriesRefreshComplete> =
  "SeriesRefreshComplete";

const route = useRoute();
const router = useRouter();
const signalR = useSignalR();

const books: Ref<SeriesOwnedBook[]> = ref([]);
const missingBooks: Ref<SeriesExpectedBook[]> = ref([]);
const ignoredBooks: Ref<SeriesExpectedBook[]> = ref([]);
const overview: Ref<SeriesOverview | null> = ref(null);
const loading = ref(false);
const seriesName = ref("");
const ignoredCollapsed = ref(true);

const candidates: Ref<SeriesMatchCandidate[]> = ref([]);
const candidatesLoaded = ref(false);
const loadingCandidates = ref(false);
const matchingCandidate = ref(false);

const includeOmnibusEditions = ref(false);
const updatingOmnibusSetting = ref(false);

const manualQuery = ref("");
const searchingManually = ref(false);

const refreshing = ref(false);
const refreshProcessed = ref(0);
const refreshTotal = ref(0);

const snackbar = ref(false);
const snackbarText = ref("");

const busy = computed(
  () =>
    loading.value ||
    refreshing.value ||
    loadingCandidates.value ||
    matchingCandidate.value ||
    searchingManually.value ||
    updatingOmnibusSetting.value,
);

const goBack = () => {
  const authorId = route.query.authorId;
  if (authorId) {
    router.push(`/library/authors/${authorId}`);
  } else {
    router.push("/library/series");
  }
};

const loadDetail = async () => {
  loading.value = true;
  try {
    const detail = await SeriesService.getSeriesDetail(seriesName.value);
    overview.value = detail.overview;
    books.value = detail.ownedBooks;
    missingBooks.value = detail.missingBooks;
    ignoredBooks.value = detail.ignoredBooks;
    includeOmnibusEditions.value = detail.overview.includeOmnibusEditions;
  } catch {
    snackbarText.value = "Failed to load series";
    snackbar.value = true;
  } finally {
    loading.value = false;
  }
};

const loadCandidates = async () => {
  loadingCandidates.value = true;
  try {
    candidates.value = await SeriesService.getMatchCandidates(seriesName.value);
    candidatesLoaded.value = true;
  } catch (e: any) {
    snackbarText.value = `Failed to fetch candidates: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  } finally {
    loadingCandidates.value = false;
  }
};

const searchManualCandidates = async () => {
  const query = manualQuery.value?.trim();
  if (!query) {
    return;
  }

  searchingManually.value = true;
  try {
    candidates.value = await SeriesService.searchMatchCandidates(
      seriesName.value,
      query,
    );
    candidatesLoaded.value = true;
    if (candidates.value.length === 0) {
      snackbarText.value = "No candidates found for that search";
      snackbar.value = true;
    }
  } catch (e: any) {
    snackbarText.value = `Search failed: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  } finally {
    searchingManually.value = false;
  }
};

const applyMatch = async (candidate: SeriesMatchCandidate) => {
  matchingCandidate.value = true;
  try {
    await SeriesService.matchSeries(
      seriesName.value,
      candidate.sourceName,
      candidate.sourceId,
      candidate.confidence,
      includeOmnibusEditions.value,
    );
    candidates.value = [];
    candidatesLoaded.value = false;
    snackbarText.value = `Matched to ${candidate.seriesName}`;
    snackbar.value = true;
    await loadDetail();
  } catch (e: any) {
    snackbarText.value = `Failed to match: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  } finally {
    matchingCandidate.value = false;
  }
};

const setIgnored = async (book: SeriesExpectedBook, ignored: boolean) => {
  try {
    if (ignored) {
      await SeriesService.ignoreExpectedBook(seriesName.value, book);
    } else {
      await SeriesService.unignoreExpectedBook(seriesName.value, book);
    }
    await loadDetail();
  } catch (e: any) {
    snackbarText.value = `Failed to update: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  }
};

const onIncludeOmnibusEditionsChanged = async (value: boolean | null) => {
  updatingOmnibusSetting.value = true;
  try {
    await SeriesService.setIncludeOmnibusEditions(
      seriesName.value,
      value ?? false,
    );
    await loadDetail();
  } catch (e: any) {
    snackbarText.value = `Failed to update: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
    includeOmnibusEditions.value = !value;
  } finally {
    updatingOmnibusSetting.value = false;
  }
};

const refreshSeries = async () => {
  refreshing.value = true;
  refreshProcessed.value = 0;
  refreshTotal.value = 0;

  try {
    await SeriesService.startRefreshSeries(seriesName.value);
  } catch (e: any) {
    refreshing.value = false;
    snackbarText.value = `Failed to start refresh: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  }
};

const onRefreshProgress = (arg: SeriesRefreshProgress) => {
  refreshProcessed.value = arg.processed;
  refreshTotal.value = arg.total;
};

const onRefreshComplete = (arg: SeriesRefreshComplete) => {
  refreshing.value = false;
  snackbarText.value = arg.stopReason
    ? `Refresh stopped: ${arg.stopReason}`
    : arg.totalFailed > 0
      ? `Refresh finished with ${arg.totalFailed} failure(s)`
      : "Refresh complete";
  snackbar.value = true;
  loadDetail();
};

signalR.on(SeriesRefreshProgressToken, onRefreshProgress);
signalR.on(SeriesRefreshCompleteToken, onRefreshComplete);

onUnmounted(() => {
  signalR.off(SeriesRefreshProgressToken, onRefreshProgress);
  signalR.off(SeriesRefreshCompleteToken, onRefreshComplete);
});

onMounted(async () => {
  seriesName.value = route.params.seriesName as string;
  await loadDetail();
});
</script>

// client/src/components/library/SeriesDetail.tsx
import { useState } from "react";
import { Link, useNavigate, useRouter } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  RefreshCw,
  Link as LinkIcon,
  ExternalLink,
  Loader2,
  ChevronRight,
  BookOpen,
  EyeOff,
  Eye,
  Search,
  Check,
  CheckCircle2,
  BookPlus,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { MissingBookCandidatesDialog } from "./MissingBookCandidatesDialog";
import { seriesApi } from "@/services/api";
import { useSignalREvent } from "@/hooks/useSignalR";
import { handleApiError } from "@/lib/api";
import { toast } from "sonner";
import type { SeriesMatchCandidate } from "@/types/Series";
import { Route } from "@/routes/library/series/$seriesName";
import { formatDate } from "@/helpers/formatHelpers";

interface SeriesRefreshCompletePayload {
  totalProcessed: number;
  totalSucceeded: number;
  totalFailed: number;
  stopReason?: string;
}

export function SeriesDetail() {
  const { seriesName } = Route.useParams();
  const { authorId } = Route.useSearch();
  const navigate = useNavigate();
  const router = useRouter();
  const queryClient = useQueryClient();
  const decodedSeriesName = decodeURIComponent(seriesName || "");

  const handleBack = () => {
    if (router.history.canGoBack()) {
      router.history.back();
    } else if (authorId) {
      void navigate({
        to: "/library/authors/$authorId",
        params: { authorId: String(authorId) },
      });
    } else {
      void navigate({ to: "/library/series" });
    }
  };

  const [refreshing, setRefreshing] = useState(false);
  const [loadingCandidates, setLoadingCandidates] = useState(false);
  const [searchingCandidates, setSearchingCandidates] = useState(false);
  const [manualQuery, setManualQuery] = useState("");
  const [candidates, setCandidates] = useState<SeriesMatchCandidate[]>([]);
  const [candidatesLoaded, setCandidatesLoaded] = useState(false);
  const [matchingCandidate, setMatchingCandidate] = useState(false);
  const [updatingOmnibus, setUpdatingOmnibus] = useState(false);
  const [ignoringBookId, setIgnoringBookId] = useState<number | null>(null);

  // Missing book candidates dialog
  const [missingCandidatesOpen, setMissingCandidatesOpen] = useState<
    false | { id: number; position?: string | null; title?: string | null }
  >(false);

  const { data: detail, isLoading: loading } = useQuery({
    queryKey: ["seriesDetail", decodedSeriesName, authorId],
    queryFn: () => seriesApi.getSeriesDetail(decodedSeriesName),
    enabled: Boolean(decodedSeriesName),
  });

  useSignalREvent<SeriesRefreshCompletePayload>("SeriesRefreshComplete", (arg) => {
    setRefreshing(false);
    const msg = arg.stopReason
      ? `Refresh stopped: ${arg.stopReason}`
      : arg.totalFailed > 0
        ? `Refresh finished with ${arg.totalFailed} failure(s)`
        : "Refresh complete";
    toast.success(msg);
    void queryClient.invalidateQueries({
      queryKey: ["seriesDetail", decodedSeriesName, authorId],
    });
  });

  const handleRefresh = async () => {
    setRefreshing(true);
    try {
      await seriesApi.startRefresh(decodedSeriesName);
      toast.success("Series refresh queued");
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
      setRefreshing(false);
    }
  };

  const handleLoadCandidates = async () => {
    setLoadingCandidates(true);
    try {
      const results = await seriesApi.getMatchCandidates(decodedSeriesName);
      setCandidates(results);
      setCandidatesLoaded(true);
      if (results.length === 0) {
        toast.info("No candidates found automatically. Try searching manually.");
      }
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setLoadingCandidates(false);
    }
  };

  const handleSearchManualCandidates = async () => {
    const q = manualQuery.trim();
    if (!q) return;
    setSearchingCandidates(true);
    try {
      const results = await seriesApi.searchMatchCandidates(decodedSeriesName, q);
      setCandidates(results);
      setCandidatesLoaded(true);
      if (results.length === 0) {
        toast.info("No candidates found for that query.");
      }
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setSearchingCandidates(false);
    }
  };

  const handleApplyMatch = async (candidate: SeriesMatchCandidate) => {
    setMatchingCandidate(true);
    try {
      await seriesApi.matchSeries(
        decodedSeriesName,
        candidate.sourceName,
        candidate.sourceId,
        candidate.confidence,
        detail?.overview.includeOmnibusEditions,
      );
      setCandidates([]);
      setCandidatesLoaded(false);
      toast.success(`Matched to ${candidate.seriesName} (${candidate.sourceName})`);
      void queryClient.invalidateQueries({
        queryKey: ["seriesDetail", decodedSeriesName, authorId],
      });
      void queryClient.invalidateQueries({ queryKey: ["series"] });
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setMatchingCandidate(false);
    }
  };

  const handleToggleOmnibus = async (checked: boolean) => {
    setUpdatingOmnibus(true);
    try {
      await seriesApi.setIncludeOmnibusEditions(decodedSeriesName, checked);
      toast.success(checked ? "Omnibus editions included" : "Omnibus editions excluded");
      void queryClient.invalidateQueries({
        queryKey: ["seriesDetail", decodedSeriesName, authorId],
      });
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setUpdatingOmnibus(false);
    }
  };

  const handleSetIgnored = async (
    book: { id: number; position?: string | null; title?: string | null },
    ignored: boolean,
  ) => {
    setIgnoringBookId(book.id);
    try {
      if (ignored) {
        await seriesApi.ignoreExpectedBook(decodedSeriesName, book.position, book.title);
        toast.success(`Ignored "${book.title || "book"}"`);
      } else {
        await seriesApi.unignoreExpectedBook(decodedSeriesName, book.position, book.title);
        toast.success(`Unignored "${book.title || "book"}"`);
      }
      void queryClient.invalidateQueries({
        queryKey: ["seriesDetail", decodedSeriesName, authorId],
      });
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setIgnoringBookId(null);
    }
  };

  if (loading) {
    return (
      <div className="text-muted-foreground flex flex-col items-center justify-center py-20">
        <Loader2 className="text-primary mb-3 h-8 w-8 animate-spin" />
        <p className="text-sm">Loading series details...</p>
      </div>
    );
  }

  if (!detail) {
    return (
      <div className="space-y-4 py-12 text-center">
        <h2 className="text-xl font-bold">Series not found</h2>
        <Button render={<Link to="/library/series" />}>Back to Series</Button>
      </div>
    );
  }

  const { overview, ownedBooks, missingBooks, ignoredBooks } = detail;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        {authorId ? (
          <Button
            variant="ghost"
            size="sm"
            className="w-full justify-start sm:w-auto"
            onClick={handleBack}
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Author
          </Button>
        ) : (
          <Button
            variant="ghost"
            size="sm"
            className="w-full justify-start sm:w-auto"
            onClick={handleBack}
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Series
          </Button>
        )}

        <div className="flex w-full flex-wrap items-center gap-2 sm:w-auto">
          <Button
            variant="outline"
            size="sm"
            className="w-full sm:w-auto"
            disabled={loadingCandidates || matchingCandidate}
            onClick={() => {
              void handleLoadCandidates();
            }}
          >
            {loadingCandidates ? (
              <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />
            ) : (
              <LinkIcon className="mr-1.5 h-4 w-4" />
            )}
            {overview.isMatched ? "Re-match to Source" : "Match to Source"}
          </Button>

          {overview.isMatched && (
            <Button
              variant="outline"
              size="sm"
              className="w-full sm:w-auto"
              disabled={refreshing}
              onClick={() => {
                void handleRefresh();
              }}
            >
              <RefreshCw className={`mr-1.5 h-4 w-4 ${refreshing ? "animate-spin" : ""}`} />
              Refresh Online
            </Button>
          )}
        </div>
      </div>

      <div className="border-border border-b pb-4">
        <h1 className="text-foreground text-2xl font-bold break-words">{decodedSeriesName}</h1>
        <div className="text-muted-foreground flex flex-wrap items-center gap-2 text-sm">
          <span>
            {ownedBooks.length} {ownedBooks.length === 1 ? "book" : "books"} owned
          </span>
          {overview.isMatched && overview.missingBookCount > 0 && (
            <span className="font-semibold text-amber-600 dark:text-amber-400">
              &middot; {overview.missingBookCount} missing
            </span>
          )}
        </div>
      </div>

      <Card>
        <CardHeader className="py-3">
          <CardTitle className="text-muted-foreground text-sm font-semibold uppercase">
            Metadata Provider Match
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-xs">
          {overview.isMatched ? (
            <div className="flex flex-wrap items-center gap-3">
              <Badge
                variant="secondary"
                className="bg-emerald-500/15 text-emerald-600 dark:text-emerald-400"
              >
                <CheckCircle2 className="mr-1 h-3.5 w-3.5" />
                Matched to {overview.matchedSourceName}
              </Badge>
              {overview.matchedSourceUrl && (
                <a
                  href={overview.matchedSourceUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-primary flex items-center hover:underline"
                >
                  <ExternalLink className="mr-1 h-3 w-3" />
                  View at source
                </a>
              )}
              {overview.matchConfidence != null && (
                <span className="text-muted-foreground">
                  Confidence: {Math.round(overview.matchConfidence * 100)}%
                </span>
              )}
              {overview.lastRefreshedAt && (
                <span className="text-muted-foreground">
                  Last refreshed: {formatDate(overview.lastRefreshedAt)}
                </span>
              )}
            </div>
          ) : (
            <p className="text-muted-foreground">
              Not matched to an online metadata provider yet. Click "Match to Source" or search
              below to associate this series.
            </p>
          )}

          <div className="flex items-center space-x-2 pt-1">
            <Checkbox
              id="includeOmnibus"
              checked={overview.includeOmnibusEditions}
              disabled={updatingOmnibus}
              onCheckedChange={(checked) => {
                void handleToggleOmnibus(Boolean(checked));
              }}
            />
            <label
              htmlFor="includeOmnibus"
              className="text-muted-foreground cursor-pointer text-xs leading-none select-none"
            >
              Include omnibus/box-set editions in missing books list
            </label>
          </div>

          <div className="border-border space-y-2 border-t pt-3">
            <label className="text-muted-foreground font-semibold">
              Search title/author or paste a series URL
            </label>
            <div className="flex max-w-xl flex-col gap-2 sm:flex-row">
              <Input
                placeholder="e.g. Harry Potter, or https://hardcover.app/series/..."
                value={manualQuery}
                onChange={(e) => setManualQuery(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    void handleSearchManualCandidates();
                  }
                }}
                className="h-8 flex-1 text-xs"
              />
              <Button
                variant="secondary"
                size="sm"
                className="h-8 w-full text-xs sm:w-auto"
                disabled={searchingCandidates || !manualQuery.trim()}
                onClick={() => {
                  void handleSearchManualCandidates();
                }}
              >
                {searchingCandidates ? (
                  <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Search className="mr-1 h-3.5 w-3.5" />
                )}
                Search
              </Button>
            </div>
          </div>

          {candidatesLoaded && (
            <div className="border-border space-y-2 border-t pt-3">
              <div className="flex items-center justify-between">
                <span className="font-semibold">Match Candidates ({candidates.length})</span>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-6 text-[11px]"
                  onClick={() => {
                    setCandidates([]);
                    setCandidatesLoaded(false);
                  }}
                >
                  Clear Candidates
                </Button>
              </div>

              {candidates.length === 0 ? (
                <p className="text-muted-foreground py-2 italic">
                  No candidates found for that search.
                </p>
              ) : (
                <div className="space-y-2">
                  {candidates.map((c) => (
                    <div
                      key={`${c.sourceName}-${c.sourceId}`}
                      className="border-border bg-muted/30 flex flex-col justify-between gap-3 rounded-md border p-2.5 sm:flex-row sm:items-center"
                    >
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-1.5 sm:gap-2">
                          <span className="font-semibold break-words">{c.seriesName}</span>
                          <Badge variant="outline" className="text-[10px]">
                            {c.sourceName}
                          </Badge>
                          <span className="text-muted-foreground text-[11px]">
                            {Math.round(c.confidence * 100)}% match
                          </span>
                        </div>
                        <div className="text-muted-foreground text-[11px] break-words">
                          {c.authors.join(", ") || "Unknown author"}
                          {c.bookCount != null ? ` · ${c.bookCount} books` : ""}
                        </div>
                      </div>
                      <div className="flex shrink-0 items-center gap-2 self-end sm:self-center">
                        {c.sourceUrl && (
                          <a
                            href={c.sourceUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-primary hover:underline"
                          >
                            <ExternalLink className="h-3.5 w-3.5" />
                          </a>
                        )}
                        <Button
                          size="sm"
                          className="h-7 text-xs"
                          disabled={matchingCandidate}
                          onClick={() => {
                            void handleApplyMatch(c);
                          }}
                        >
                          {matchingCandidate ? (
                            <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                          ) : (
                            <Check className="mr-1 h-3 w-3" />
                          )}
                          Apply Match
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      <div className="space-y-4">
        <h2 className="text-foreground text-lg font-bold">Owned Books ({ownedBooks.length})</h2>
        {ownedBooks.length === 0 ? (
          <p className="text-muted-foreground text-sm">No books owned.</p>
        ) : (
          <div className="space-y-2">
            {ownedBooks.map((b) => (
              <Link
                key={b.id}
                to="/library/book/$bookId"
                params={{ bookId: String(b.id) }}
                className="group border-border bg-card hover:bg-muted/50 focus-visible:ring-ring flex cursor-pointer items-center justify-between rounded-lg border p-3 transition-colors focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none"
              >
                <div className="flex min-w-0 flex-1 items-center gap-3">
                  <BookOpen className="text-primary h-4 w-4 shrink-0" />
                  <div className="min-w-0 flex-1">
                    <span className="text-foreground font-semibold break-words">
                      {b.seriesPart ? `#${b.seriesPart} ` : ""}
                      {b.bookName}
                    </span>
                    <div className="text-muted-foreground text-xs break-words">
                      {b.authors.join(", ")}
                      {b.year ? ` (${b.year})` : ""}
                    </div>
                  </div>
                </div>
                <ChevronRight className="text-muted-foreground group-hover:text-foreground h-4 w-4 shrink-0" />
              </Link>
            ))}
          </div>
        )}
      </div>

      {overview.isMatched && (
        <div className="space-y-4">
          <h2 className="text-lg font-bold text-amber-600 dark:text-amber-400">
            Missing Books ({missingBooks.length})
          </h2>
          {missingBooks.length === 0 ? (
            <p className="text-muted-foreground text-xs">
              No missing books detected in this series.
            </p>
          ) : (
            <div className="space-y-2">
              {missingBooks.map((mb) => (
                <div
                  key={mb.id}
                  className="flex flex-col justify-between gap-2 rounded-lg border border-amber-500/20 bg-amber-500/5 p-3 text-xs sm:flex-row sm:items-center"
                >
                  <div className="min-w-0 flex-1">
                    <span className="text-foreground font-semibold break-words">
                      {mb.position ? `Part ${mb.position} — ` : ""}
                      {mb.title}
                    </span>
                    {mb.year && <span className="text-muted-foreground"> ({mb.year})</span>}
                  </div>
                  <div className="flex shrink-0 items-center gap-2 self-end sm:self-center">
                    {mb.sourceUrl && (
                      <a
                        href={mb.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary flex items-center hover:underline"
                      >
                        <ExternalLink className="mr-1 h-3 w-3" />
                        Source
                      </a>
                    )}
                    <Button
                      variant="secondary"
                      size="sm"
                      className="h-6 text-[11px]"
                      onClick={() => {
                        setMissingCandidatesOpen({
                          id: mb.id,
                          position: mb.position,
                          title: mb.title,
                        });
                      }}
                    >
                      <BookPlus className="mr-1 h-3 w-3" />
                      Find in Library
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 text-[11px]"
                      disabled={ignoringBookId === mb.id}
                      onClick={() => {
                        void handleSetIgnored(mb, true);
                      }}
                    >
                      {ignoringBookId === mb.id ? (
                        <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                      ) : (
                        <EyeOff className="mr-1 h-3 w-3" />
                      )}
                      Ignore
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {overview.isMatched && ignoredBooks.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-muted-foreground text-lg font-bold">
            Ignored Books ({ignoredBooks.length})
          </h2>
          <div className="space-y-2">
            {ignoredBooks.map((ib) => (
              <div
                key={ib.id}
                className="border-border bg-card flex flex-col justify-between gap-2 rounded-lg border p-3 text-xs opacity-75 sm:flex-row sm:items-center"
              >
                <div className="min-w-0 flex-1">
                  <span className="text-muted-foreground break-words">
                    {ib.position ? `Part ${ib.position} — ` : ""}
                    {ib.title}
                  </span>
                  {ib.year && <span className="text-muted-foreground"> ({ib.year})</span>}
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-6 self-end text-[11px] sm:self-center"
                  disabled={ignoringBookId === ib.id}
                  onClick={() => {
                    void handleSetIgnored(ib, false);
                  }}
                >
                  {ignoringBookId === ib.id ? (
                    <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                  ) : (
                    <Eye className="mr-1 h-3 w-3" />
                  )}
                  Unignore
                </Button>
              </div>
            ))}
          </div>
        </div>
      )}

      <MissingBookCandidatesDialog
        open={typeof missingCandidatesOpen === "object"}
        onOpenChange={(open) => {
          setMissingCandidatesOpen(open ? missingCandidatesOpen : false);
        }}
        seriesName={decodedSeriesName}
        missingBook={
          typeof missingCandidatesOpen === "object"
            ? {
                id: missingCandidatesOpen.id,
                position: missingCandidatesOpen.position,
                title: missingCandidatesOpen.title,
              }
            : {
                id: 0,
                position: null,
                title: null,
              }
        }
      />
    </div>
  );
}

export default SeriesDetail;
