// client/src/components/library/SeriesOverview.vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <v-btn
          variant="text"
          prepend-icon="mdi-arrow-left"
          to="/library"
        >
          Back to Library
        </v-btn>
      </v-col>
    </v-row>
    <v-row>
      <v-col>
        <h2 class="text-h5 mb-1">Series</h2>
        <div class="text-caption text-medium-emphasis">
          Every series in your library. Match a series to a metadata source to
          see which of its books you are missing.
        </div>
      </v-col>
    </v-row>

    <v-row>
      <v-col
        cols="12"
        md="6"
      >
        <v-text-field
          v-model="filter"
          label="Filter series"
          prepend-inner-icon="mdi-magnify"
          clearable
          hide-details
          density="compact"
        />
      </v-col>
      <v-col
        cols="12"
        md="6"
        class="d-flex align-center flex-wrap ga-2"
      >
        <v-btn
          :disabled="loading"
          :loading="loading"
          prepend-icon="mdi-refresh"
          @click="loadSeries()"
        >
          Reload
        </v-btn>
        <v-btn
          :disabled="busy || unmatchedSeries.length === 0"
          prepend-icon="mdi-link-variant"
          @click="matchDialogOpen = true"
        >
          Bulk match ({{ unmatchedSeries.length }})
        </v-btn>
        <v-btn
          :disabled="busy || matchedCount === 0"
          prepend-icon="mdi-cloud-refresh"
          @click="refreshAll()"
        >
          Refresh all series
        </v-btn>
      </v-col>
    </v-row>

    <v-row v-if="refreshing">
      <v-col cols="12">
        <OperationProgressBar
          class="mt-3"
          :processed="refreshProcessed"
          :total="refreshTotal"
        />
        <div class="text-caption">
          Succeeded: {{ refreshSucceeded }}, Failed: {{ refreshFailed }}
        </div>
      </v-col>
    </v-row>

    <v-row>
      <v-col>
        <v-table v-if="filteredSeries.length">
          <thead>
            <tr>
              <th class="text-left">Series</th>
              <th class="text-left">Author</th>
              <th class="text-right">Owned</th>
              <th class="text-right">Missing</th>
              <th class="text-left">Match</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="series in filteredSeries"
              :key="series.name"
              class="cursor-pointer"
              @click="openSeries(series)"
            >
              <td>{{ series.name }}</td>
              <td class="text-medium-emphasis">
                {{ series.authors.join(", ") || "—" }}
              </td>
              <td class="text-right">{{ series.ownedBookCount }}</td>
              <td class="text-right">
                <v-chip
                  v-if="series.isMatched && series.missingBookCount > 0"
                  size="small"
                  color="warning"
                >
                  {{ series.missingBookCount }}
                </v-chip>
                <span v-else-if="series.isMatched">0</span>
                <span
                  v-else
                  class="text-medium-emphasis"
                  >—</span
                >
              </td>
              <td>
                <v-chip
                  v-if="series.isMatched"
                  size="small"
                  color="success"
                  variant="tonal"
                >
                  {{ series.matchedSourceName }}
                  <span
                    v-if="series.matchConfidence != null"
                    class="ml-1"
                  >
                    ({{ Math.round(series.matchConfidence * 100) }}%)
                  </span>
                </v-chip>
                <v-chip
                  v-else
                  size="small"
                  variant="tonal"
                >
                  Unmatched
                </v-chip>
              </td>
            </tr>
          </tbody>
        </v-table>
        <div
          v-else-if="loading"
          class="text-center"
        >
          <v-progress-circular indeterminate />
        </div>
        <div
          v-else
          class="text-center"
        >
          No series found
        </div>
      </v-col>
    </v-row>

    <SeriesMatchDialog
      v-model="matchDialogOpen"
      :series="unmatchedSeries"
      @matched="loadSeries()"
    />

    <v-snackbar
      v-model="snackbar"
      :timeout="4000"
    >
      {{ snackbarText }}
    </v-snackbar>
  </v-container>
</template>

<script setup lang="ts">
import { computed, onMounted, Ref, ref } from "vue";
import { useRouter } from "vue-router";
import SeriesService from "../../services/SeriesService";
import { SeriesOverview } from "../../types/Series";
import SeriesMatchDialog from "./SeriesMatchDialog.vue";
import OperationProgressBar from "../OperationProgressBar.vue";
import { HubEventToken } from "@/signalr/hub";
import { useOperationProgress } from "../../composables/useOperationProgress";
import { SeriesRefreshProgress } from "../../signalr/SeriesRefreshProgress";
import { SeriesRefreshComplete } from "../../signalr/SeriesRefreshComplete";
import { foldAccents } from "../../helpers/similarValueMatcher";

const SeriesRefreshProgressToken: HubEventToken<SeriesRefreshProgress> =
  "SeriesRefreshProgress";
const SeriesRefreshCompleteToken: HubEventToken<SeriesRefreshComplete> =
  "SeriesRefreshComplete";

const router = useRouter();

const series: Ref<SeriesOverview[]> = ref([]);
const filter = ref("");
const loading = ref(false);

const refreshSucceeded = ref(0);
const refreshFailed = ref(0);

const matchDialogOpen = ref(false);
const snackbar = ref(false);
const snackbarText = ref("");

const busy = computed(() => loading.value || refreshing.value);

const filteredSeries = computed(() => {
  if (!filter.value) return series.value;
  const q = foldAccents(filter.value.toLowerCase());
  return series.value.filter(
    (s) =>
      foldAccents(s.name.toLowerCase()).includes(q) ||
      s.authors.some((a) => foldAccents(a.toLowerCase()).includes(q)),
  );
});

const unmatchedSeries = computed(() =>
  series.value.filter((s) => !s.isMatched),
);

const matchedCount = computed(
  () => series.value.filter((s) => s.isMatched).length,
);

const openSeries = (s: SeriesOverview) => {
  router.push(`/library/series/${encodeURIComponent(s.name)}`);
};

const loadSeries = async () => {
  loading.value = true;
  try {
    series.value = await SeriesService.getAllSeries();
  } catch {
    snackbarText.value = "Failed to load series";
    snackbar.value = true;
  } finally {
    loading.value = false;
  }
};

const {
  isRunning: refreshing,
  processed: refreshProcessed,
  total: refreshTotal,
  start: startRefreshing,
} = useOperationProgress<SeriesRefreshProgress, SeriesRefreshComplete>({
  key: "series-refresh",
  progressToken: SeriesRefreshProgressToken,
  completeToken: SeriesRefreshCompleteToken,
  getProcessed: (arg) => arg.processed,
  getTotal: (arg) => arg.total,
  onProgress: (arg) => {
    refreshSucceeded.value = arg.succeeded;
    refreshFailed.value = arg.failed;
  },
  onComplete: (arg) => {
    let msg = arg.stopReason
      ? `Refresh stopped after ${arg.totalProcessed} series: ${arg.stopReason}`
      : `Refresh complete: ${arg.totalSucceeded} of ${arg.totalProcessed} series updated`;
    if (arg.totalFailed > 0) {
      msg += ` (${arg.totalFailed} failed)`;
    }
    snackbarText.value = msg;
    snackbar.value = true;
    loadSeries();
  },
});

const refreshAll = async () => {
  startRefreshing();
  refreshSucceeded.value = 0;
  refreshFailed.value = 0;

  try {
    await SeriesService.startRefreshAll();
  } catch (e: any) {
    refreshing.value = false;
    snackbarText.value = `Failed to start refresh: ${e?.response?.data ?? e.message}`;
    snackbar.value = true;
  }
};

onMounted(() => {
  loadSeries();
});
</script>

<style scoped>
.cursor-pointer {
  cursor: pointer;
}
</style>

// client/src/components/library/SeriesOverview.tsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  BookMarked,
  Search,
  RefreshCw,
  CheckCircle2,
  AlertCircle,
  Loader2,
  ChevronRight,
  Layers,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { OperationProgressBar } from "@/components/OperationProgressBar";
import { SeriesMatchDialog } from "./SeriesMatchDialog";
import { seriesApi } from "@/services/api";
import { useSignalREvent } from "@/hooks/useSignalR";
import { foldAccents } from "@/helpers/similarValueMatcher";
import { handleApiError } from "@/lib/api";
import { toast } from "sonner";

interface SeriesRefreshProgressPayload {
  processed: number;
  total: number;
  succeeded: number;
  failed: number;
}

interface SeriesRefreshCompletePayload {
  totalProcessed: number;
  totalSucceeded: number;
  totalFailed: number;
  stopReason?: string;
}

export function SeriesOverviewPage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [filter, setFilter] = useState("");

  const [refreshing, setRefreshing] = useState(false);
  const [refreshProgress, setRefreshProgress] = useState<SeriesRefreshProgressPayload | null>(null);
  const [matchDialogOpen, setMatchDialogOpen] = useState(false);

  const {
    data: seriesList = [],
    isLoading: loading,
    refetch,
  } = useQuery({
    queryKey: ["series"],
    queryFn: () => seriesApi.getAllSeries(),
  });

  useSignalREvent<SeriesRefreshProgressPayload>("SeriesRefreshProgress", (data) => {
    setRefreshing(true);
    setRefreshProgress(data);
  });

  useSignalREvent<SeriesRefreshCompletePayload>("SeriesRefreshComplete", (arg) => {
    setRefreshing(false);
    setRefreshProgress(null);
    const msg = arg.stopReason
      ? `Refresh stopped after ${arg.totalProcessed} series: ${arg.stopReason}`
      : `Refresh complete: ${arg.totalSucceeded} of ${arg.totalProcessed} series updated${
          arg.totalFailed > 0 ? ` (${arg.totalFailed} failed)` : ""
        }`;
    toast.success(msg);
    void queryClient.invalidateQueries({ queryKey: ["series"] });
  });

  const handleRefreshAll = async () => {
    setRefreshing(true);
    try {
      await seriesApi.startRefreshAll();
      toast.success("Refreshing all series in background");
    } catch (err: unknown) {
      setRefreshing(false);
      toast.error(handleApiError(err).message);
    }
  };

  const unmatchedSeries = seriesList.filter((s) => !s.isMatched);
  const matchedCount = seriesList.filter((s) => s.isMatched).length;

  const filteredSeries = seriesList.filter((s) => {
    if (!filter.trim()) return true;
    const q = foldAccents(filter.trim().toLowerCase());
    const nameMatch = foldAccents(s.name.toLowerCase()).includes(q);
    const authorMatch = s.authors.some((a) => foldAccents(a.toLowerCase()).includes(q));
    return nameMatch || authorMatch;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <Button variant="ghost" size="sm" render={<Link to="/library" />}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Library
        </Button>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              void refetch();
            }}
            disabled={loading || refreshing}
          >
            <RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />
            Reload
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={() => setMatchDialogOpen(true)}
            disabled={loading || refreshing || unmatchedSeries.length === 0}
          >
            <Sparkles className="mr-2 h-4 w-4" />
            Bulk Match ({unmatchedSeries.length})
          </Button>

          <Button
            variant="default"
            size="sm"
            onClick={() => {
              void handleRefreshAll();
            }}
            disabled={loading || refreshing || matchedCount === 0}
          >
            <Layers className="mr-2 h-4 w-4" />
            {refreshing ? "Refreshing All..." : "Refresh All Series"}
          </Button>
        </div>
      </div>

      <div>
        <h1 className="text-foreground flex items-center gap-2 text-2xl font-bold">
          <BookMarked className="text-primary h-6 w-6" />
          Series ({seriesList.length})
        </h1>
        <p className="text-muted-foreground text-sm">
          Every series in your library. Match series to metadata providers to identify missing parts
          and maintain reading orders.
        </p>
      </div>

      {refreshing && refreshProgress && (
        <OperationProgressBar
          processed={refreshProgress.processed}
          total={refreshProgress.total}
          label={`Refreshing series metadata (${refreshProgress.succeeded} succeeded, ${refreshProgress.failed} failed)`}
        />
      )}

      <div className="relative max-w-md">
        <Search className="text-muted-foreground absolute top-2.5 left-3 h-4 w-4" />
        <Input
          placeholder="Filter series or authors..."
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className="pl-9"
        />
      </div>

      {loading && seriesList.length === 0 ? (
        <div className="text-muted-foreground flex flex-col items-center justify-center py-16">
          <Loader2 className="text-primary mb-3 h-8 w-8 animate-spin" />
          <p className="text-sm">Loading series...</p>
        </div>
      ) : filteredSeries.length === 0 ? (
        <Card className="p-12 text-center">
          <BookMarked className="text-muted-foreground/40 mx-auto mb-3 h-12 w-12" />
          <h3 className="text-foreground text-lg font-medium">No series found</h3>
          <p className="text-muted-foreground mt-1 text-sm">
            {filter
              ? "No series match your search filter."
              : "No audiobooks with series tags have been organized yet."}
          </p>
        </Card>
      ) : (
        <div className="space-y-2">
          {filteredSeries.map((s) => (
            <div
              key={s.name}
              onClick={() => {
                void navigate(`/library/series/${encodeURIComponent(s.name)}`);
              }}
              className="group border-border bg-card hover:bg-muted/50 flex cursor-pointer items-center justify-between rounded-lg border p-3 transition-colors"
            >
              <div className="min-w-0">
                <div className="flex items-center gap-2">
                  <span className="text-foreground truncate font-semibold">{s.name}</span>
                  {s.isMatched ? (
                    <Badge
                      variant="secondary"
                      className="gap-1 bg-emerald-500/15 text-[11px] text-emerald-600 dark:text-emerald-400"
                    >
                      <CheckCircle2 className="h-3 w-3" />
                      {s.matchedSourceName}
                      {s.matchConfidence != null && (
                        <span className="ml-0.5 opacity-75">
                          ({Math.round(s.matchConfidence * 100)}%)
                        </span>
                      )}
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="text-muted-foreground text-[11px]">
                      Unmatched
                    </Badge>
                  )}
                </div>

                <div className="text-muted-foreground flex flex-wrap items-center gap-x-2 text-xs">
                  {s.authors.length > 0 && <span>By {s.authors.join(", ")} &middot;</span>}
                  <span>
                    {s.ownedBookCount} {s.ownedBookCount === 1 ? "book" : "books"} owned
                  </span>
                  {s.isMatched && s.missingBookCount > 0 && (
                    <span className="font-medium text-amber-600 dark:text-amber-400">
                      &middot; {s.missingBookCount} missing
                    </span>
                  )}
                </div>
              </div>

              <div className="flex shrink-0 items-center gap-3">
                {s.missingBookCount > 0 && (
                  <Badge variant="destructive" className="gap-1 text-xs">
                    <AlertCircle className="h-3 w-3" />
                    {s.missingBookCount} missing
                  </Badge>
                )}
                <ChevronRight className="text-muted-foreground group-hover:text-foreground h-4 w-4" />
              </div>
            </div>
          ))}
        </div>
      )}

      <SeriesMatchDialog
        open={matchDialogOpen}
        onOpenChange={setMatchDialogOpen}
        series={unmatchedSeries}
        onMatched={() => {
          void queryClient.invalidateQueries({ queryKey: ["series"] });
        }}
      />
    </div>
  );
}

export default SeriesOverviewPage;
