// client/src/components/DiffDisplay.vue
<template>
  <div class="diff-display">
    <span
      v-for="(part, i) in diffParts"
      :key="i"
      :class="{
        'diff-added': part.added,
        'diff-removed': part.removed,
      }"
      >{{ part.value }}</span
    >
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { diffChars, type Change } from "diff";

const props = defineProps<{
  expected: string;
  actual: string;
}>();

const diffParts = computed((): Change[] => {
  return diffChars(props.actual, props.expected);
});
</script>

<style scoped>
.diff-display {
  font-family: monospace;
  font-size: 0.85em;
  word-break: break-all;
  white-space: pre-wrap;
}

.diff-added {
  background-color: rgba(76, 175, 80, 0.3);
  border-radius: 2px;
}

.diff-removed {
  background-color: rgba(244, 67, 54, 0.3);
  text-decoration: line-through;
  border-radius: 2px;
}
</style>

// client/src/components/DiffDisplay.tsx
import { diffChars, type Change } from "diff";

interface DiffDisplayProps {
  expected?: string;
  actual?: string;
  original?: string;
  modified?: string;
}

export function DiffDisplay({ expected, actual, original, modified }: DiffDisplayProps) {
  const oldText = actual ?? original ?? "";
  const newText = expected ?? modified ?? "";
  const diffs: Change[] = diffChars(oldText, newText);

  return (
    <div className="border-border bg-muted/50 rounded-md border p-3 font-mono text-xs leading-relaxed break-all whitespace-pre-wrap">
      {diffs.map((part, index) => {
        if (part.added) {
          return (
            <span
              key={index}
              className="rounded bg-emerald-500/20 px-0.5 font-semibold text-emerald-600 dark:text-emerald-400"
            >
              {part.value}
            </span>
          );
        }
        if (part.removed) {
          return (
            <span
              key={index}
              className="rounded bg-rose-500/20 px-0.5 text-rose-600 line-through dark:text-rose-400"
            >
              {part.value}
            </span>
          );
        }
        return <span key={index}>{part.value}</span>;
      })}
    </div>
  );
}

export default DiffDisplay;
