// client/src/components/LibraryConsistency.vue
<template>
  <v-container>
    <v-row class="text-center">
      <v-col class="mb-5">
        <h2 class="headline font-weight-bold mb-5">Library Consistency</h2>
      </v-col>
    </v-row>
    <v-row>
      <v-col cols="12">
        <v-btn
          class="mr-3"
          to="/library"
          prepend-icon="mdi-arrow-left"
        >
          Back to Library
        </v-btn>
        <v-btn
          :disabled="checking"
          :loading="checking"
          @click="startCheck()"
          prepend-icon="mdi-check-decagram"
        >
          Run Check
        </v-btn>
        <div class="text-caption text-medium-emphasis mt-2">
          Verifies that every book in the library has the correct file path,
          sidecar metadata files (desc.txt, reader.txt), and a cover image, and
          flags leftover folders with no audio file.
        </div>
      </v-col>
    </v-row>
    <v-row v-if="checking">
      <v-col cols="12">
        <OperationProgressBar
          class="mt-3"
          :processed="checkBooksChecked"
          :total="checkTotalBooks"
        />
        <div class="text-caption mt-1">{{ checkMessage }}</div>
        <div class="text-caption">Issues found: {{ checkIssuesFound }}</div>
      </v-col>
    </v-row>
    <v-row v-if="checkComplete">
      <v-col cols="12">
        <v-alert
          type="info"
          class="mt-3"
          closable
          @click:close="checkComplete = false"
        >
          Check complete: {{ completeTotalBooks }} books checked,
          {{ completeTotalIssues }} issues found.
        </v-alert>
      </v-col>
    </v-row>
    <v-row v-if="issues.length > 0">
      <v-col cols="12">
        <h3 class="text-h6 mb-3">Issues ({{ issues.length }})</h3>
        <v-expansion-panels>
          <v-expansion-panel
            v-for="group in groupedByType"
            :key="group.issueType"
          >
            <v-expansion-panel-title>
              <v-row align="center">
                <v-col class="d-flex align-center">
                  <v-icon
                    :icon="getIssueIcon(group.issueType)"
                    class="mr-2"
                  />
                  {{ getIssueTypeLabel(group.issueType) }}
                  <v-icon
                    icon="mdi-information-outline"
                    size="small"
                    class="ml-2 text-medium-emphasis"
                    @click.stop
                  />
                  <v-tooltip
                    activator="parent"
                    location="bottom"
                    max-width="320"
                  >
                    {{ getBulkResolveDescription(group.issueType) }}
                  </v-tooltip>
                </v-col>
                <v-col cols="auto">
                  <v-chip
                    size="small"
                    color="warning"
                  >
                    {{ group.issues.length }}
                  </v-chip>
                </v-col>
              </v-row>
            </v-expansion-panel-title>
            <v-expansion-panel-text>
              <div
                class="d-flex align-center justify-space-between mb-2 flex-wrap ga-2"
              >
                <div class="d-flex align-center">
                  <v-checkbox
                    :model-value="isGroupFullySelected(group)"
                    :indeterminate="isGroupPartiallySelected(group)"
                    density="compact"
                    hide-details
                    label="Select all visible"
                    @update:model-value="toggleSelectAllVisible(group)"
                  />
                  <span
                    v-if="selectedCountInGroup(group) > 0"
                    class="text-caption text-medium-emphasis ml-2"
                  >
                    {{ selectedCountInGroup(group) }} selected
                  </span>
                </div>
                <div>
                  <v-btn
                    v-if="selectedCountInGroup(group) > 0"
                    size="small"
                    variant="outlined"
                    color="primary"
                    class="mr-2"
                    :loading="resolvingSelectedTypes.has(group.issueType)"
                    :disabled="resolvingSelectedTypes.has(group.issueType)"
                    @click.stop="onResolveSelectedClick(group)"
                  >
                    Resolve Selected ({{ selectedCountInGroup(group) }})
                  </v-btn>
                  <v-btn
                    size="small"
                    variant="outlined"
                    :loading="resolvingTypes.has(group.issueType)"
                    :disabled="resolvingTypes.has(group.issueType)"
                    @click.stop="onBulkResolveClick(group.issueType)"
                  >
                    Resolve All {{ group.issues.length }}
                  </v-btn>
                </div>
              </div>
              <v-list density="compact">
                <v-list-item
                  v-for="issue in group.visibleIssues"
                  :key="issue.id"
                  class="issue-item"
                >
                  <template v-slot:prepend>
                    <v-checkbox
                      :model-value="selectedIssueIds.has(issue.id)"
                      density="compact"
                      hide-details
                      class="mr-1"
                      @click.stop
                      @update:model-value="toggleIssueSelected(issue.id)"
                    />
                    <v-icon :icon="getIssueIcon(issue.issueType)" />
                  </template>
                  <v-list-item-title class="text-wrap">
                    <router-link
                      :to="`/library/book/${issue.audiobookId}`"
                      class="text-decoration-none"
                    >
                      {{ issue.authors.join(", ") }} &mdash;
                      {{ issue.bookName }}
                    </router-link>
                  </v-list-item-title>
                  <v-list-item-subtitle class="issue-subtitle text-wrap">
                    <div>{{ issue.description }}</div>
                    <DiffDisplay
                      v-if="issue.expectedValue && issue.actualValue"
                      :expected="issue.expectedValue"
                      :actual="issue.actualValue"
                    />
                    <template v-else>
                      <div
                        v-if="issue.expectedValue"
                        class="text-wrap"
                      >
                        Expected: {{ issue.expectedValue }}
                      </div>
                      <div
                        v-if="issue.actualValue"
                        class="text-wrap"
                      >
                        Actual: {{ issue.actualValue }}
                      </div>
                    </template>
                  </v-list-item-subtitle>
                  <template v-slot:append>
                    <v-btn
                      size="small"
                      variant="outlined"
                      :loading="resolvingIds.has(issue.id)"
                      @click.stop="onResolveClick(issue)"
                    >
                      Resolve
                    </v-btn>
                    <v-tooltip
                      activator="parent"
                      location="left"
                      max-width="320"
                    >
                      {{ getBulkResolveDescription(issue.issueType) }}
                    </v-tooltip>
                  </template>
                </v-list-item>
              </v-list>
              <div
                v-if="group.issues.length > group.displayCount"
                class="text-center mt-2"
              >
                <v-btn
                  variant="text"
                  size="small"
                  @click="showMore(group.issueType)"
                >
                  Show more ({{ group.issues.length - group.displayCount }}
                  remaining)
                </v-btn>
              </div>
            </v-expansion-panel-text>
          </v-expansion-panel>
        </v-expansion-panels>
      </v-col>
    </v-row>
    <v-row v-if="orphanDirectories.length > 0">
      <v-col cols="12">
        <h3 class="text-h6 mb-3">
          Orphaned Directories ({{ orphanDirectories.length }})
        </h3>
        <v-card variant="outlined">
          <v-card-text>
            <div class="d-flex justify-end mb-2">
              <v-btn
                size="small"
                variant="outlined"
                :loading="resolvingAllOrphans"
                :disabled="resolvingAllOrphans"
                @click="onBulkResolveOrphansClick()"
              >
                Delete All {{ orphanDirectories.length }}
              </v-btn>
            </div>
            <v-list density="compact">
              <v-list-item
                v-for="dir in orphanDirectories"
                :key="dir.id"
              >
                <template v-slot:prepend>
                  <v-icon icon="mdi-folder-remove" />
                </template>
                <v-list-item-title class="text-wrap">
                  {{ dir.directoryPath }}
                </v-list-item-title>
                <template v-slot:append>
                  <v-btn
                    size="small"
                    variant="outlined"
                    :loading="resolvingOrphanIds.has(dir.id)"
                    @click.stop="onResolveOrphanClick(dir)"
                  >
                    Delete
                  </v-btn>
                </template>
              </v-list-item>
            </v-list>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
    <v-row
      v-if="
        !checking &&
        !checkComplete &&
        issues.length === 0 &&
        orphanDirectories.length === 0
      "
    >
      <v-col cols="12">
        <div class="text-center mt-5">
          Run a consistency check to find issues in your library.
        </div>
      </v-col>
    </v-row>

    <v-dialog
      v-model="orphanConfirmDialog"
      max-width="500"
    >
      <v-card>
        <v-card-title>Confirm Deletion</v-card-title>
        <v-card-text>
          <template v-if="pendingOrphanBulk">
            This will permanently delete
            <strong>all {{ orphanDirectories.length }}</strong>
            orphaned directories (folders with no audio file) and everything in
            them. This action cannot be undone.
          </template>
          <template v-else-if="pendingOrphanDirectory">
            This will permanently delete
            <strong>{{ pendingOrphanDirectory.directoryPath }}</strong>
            and everything in it. This action cannot be undone.
          </template>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="cancelOrphanConfirm()">Cancel</v-btn>
          <v-btn
            color="error"
            @click="confirmOrphanResolve()"
          >
            Delete
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-dialog
      v-model="confirmDialog"
      max-width="500"
    >
      <v-card>
        <v-card-title>Confirm Resolution</v-card-title>
        <v-card-text>
          <template
            v-if="
              pendingSelectedType === 'MissingMediaFile' ||
              pendingBulkType === 'MissingMediaFile'
            "
          >
            This will remove
            <strong>
              {{ pendingSelectedType ? "the selected" : "all" }}
              {{
                pendingSelectedType
                  ? pendingSelectedIssueIds.length
                  : pendingBulkCount
              }}
              audiobooks
            </strong>
            with missing media files from the database and clean up empty
            directories. This action cannot be undone.
          </template>
          <template v-else-if="pendingSelectedType">
            This will resolve the selected
            <strong>{{ pendingSelectedIssueIds.length }}</strong>
            {{ getIssueTypeLabel(pendingSelectedType) }} issue{{
              pendingSelectedIssueIds.length === 1 ? "" : "s"
            }}.
            {{ getBulkResolveDescription(pendingSelectedType) }}
          </template>
          <template v-else-if="pendingBulkType">
            This will resolve all
            <strong>{{ pendingBulkCount }}</strong>
            {{ getIssueTypeLabel(pendingBulkType) }} issues.
            {{ getBulkResolveDescription(pendingBulkType) }}
          </template>
          <template v-else>
            This will remove the audiobook from the database and clean up empty
            directories. This action cannot be undone.
          </template>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="cancelConfirm()">Cancel</v-btn>
          <v-btn
            color="error"
            @click="confirmResolve()"
          >
            {{
              pendingSelectedType
                ? "Resolve Selected"
                : pendingBulkType
                  ? "Resolve All"
                  : "Remove"
            }}
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-snackbar
      v-model="snackbar"
      :timeout="3000"
    >
      {{ snackbarText }}
    </v-snackbar>
  </v-container>
</template>

<script setup lang="ts">
import { computed, Ref, ref, onMounted, reactive } from "vue";
import ConsistencyService from "../services/ConsistencyService";
import ConsistencyIssue from "../types/ConsistencyIssue";
import OrphanDirectory from "../types/OrphanDirectory";
import DiffDisplay from "./DiffDisplay.vue";
import OperationProgressBar from "./OperationProgressBar.vue";
import { HubEventToken } from "@/signalr/hub";
import { useOperationProgress } from "../composables/useOperationProgress";
import { ConsistencyCheckProgress } from "../signalr/ConsistencyCheckProgress";
import { ConsistencyCheckComplete } from "../signalr/ConsistencyCheckComplete";

const PAGE_SIZE = 50;

const ConsistencyCheckProgressToken: HubEventToken<ConsistencyCheckProgress> =
  "ConsistencyCheckProgress";
const ConsistencyCheckCompleteToken: HubEventToken<ConsistencyCheckComplete> =
  "ConsistencyCheckComplete";

const issues: Ref<ConsistencyIssue[]> = ref([]);
const checkMessage: Ref<string> = ref("");
const checkIssuesFound: Ref<number> = ref(0);
const checkComplete: Ref<boolean> = ref(false);
const completeTotalBooks: Ref<number> = ref(0);
const completeTotalIssues: Ref<number> = ref(0);
const resolvingIds: Ref<Set<number>> = ref(new Set());
const resolvingTypes: Ref<Set<string>> = ref(new Set());
const confirmDialog: Ref<boolean> = ref(false);
const pendingResolveIssue: Ref<ConsistencyIssue | null> = ref(null);
const pendingBulkType: Ref<string | null> = ref(null);
const pendingBulkCount: Ref<number> = ref(0);
const selectedIssueIds: Ref<Set<number>> = ref(new Set());
const resolvingSelectedTypes: Ref<Set<string>> = ref(new Set());
const pendingSelectedType: Ref<string | null> = ref(null);
const pendingSelectedIssueIds: Ref<number[]> = ref([]);
const snackbar: Ref<boolean> = ref(false);
const snackbarText: Ref<string> = ref("");
const displayCounts: Record<string, number> = reactive({});

const orphanDirectories: Ref<OrphanDirectory[]> = ref([]);
const resolvingOrphanIds: Ref<Set<number>> = ref(new Set());
const resolvingAllOrphans: Ref<boolean> = ref(false);
const orphanConfirmDialog: Ref<boolean> = ref(false);
const pendingOrphanDirectory: Ref<OrphanDirectory | null> = ref(null);
const pendingOrphanBulk: Ref<boolean> = ref(false);

interface TypeGroup {
  issueType: string;
  issues: ConsistencyIssue[];
  displayCount: number;
  visibleIssues: ConsistencyIssue[];
}

const groupedByType = computed((): TypeGroup[] => {
  const groups = new Map<string, ConsistencyIssue[]>();
  for (const issue of issues.value) {
    if (!groups.has(issue.issueType)) {
      groups.set(issue.issueType, []);
    }
    groups.get(issue.issueType)!.push(issue);
  }
  return Array.from(groups.entries()).map(([issueType, typeIssues]) => {
    const displayCount = displayCounts[issueType] || PAGE_SIZE;
    return {
      issueType,
      issues: typeIssues,
      displayCount,
      visibleIssues: typeIssues.slice(0, displayCount),
    };
  });
});

const showMore = (issueType: string) => {
  const current = displayCounts[issueType] || PAGE_SIZE;
  displayCounts[issueType] = current + PAGE_SIZE;
};

const getIssueTypeLabel = (issueType: string): string => {
  switch (issueType) {
    case "MissingMediaFile":
      return "Missing Media Files";
    case "WrongFilePath":
      return "Wrong File Paths";
    case "MissingDescTxt":
      return "Missing Description Files";
    case "IncorrectDescTxt":
      return "Incorrect Description Files";
    case "MissingReaderTxt":
      return "Missing Reader Files";
    case "IncorrectReaderTxt":
      return "Incorrect Reader Files";
    case "MissingCoverFile":
      return "Missing Cover Files";
    case "TagMismatch":
      return "Tag Mismatches";
    default:
      return issueType;
  }
};

const {
  isRunning: checking,
  processed: checkBooksChecked,
  total: checkTotalBooks,
  start: startChecking,
} = useOperationProgress<ConsistencyCheckProgress, ConsistencyCheckComplete>({
  key: "consistency-check",
  progressToken: ConsistencyCheckProgressToken,
  completeToken: ConsistencyCheckCompleteToken,
  getProcessed: (arg) => arg.booksChecked,
  getTotal: (arg) => arg.totalBooks,
  onProgress: (arg) => {
    checkMessage.value = arg.message;
    checkIssuesFound.value = arg.issuesFound;
  },
  onComplete: (arg) => {
    checkComplete.value = true;
    completeTotalBooks.value = arg.totalBooksChecked;
    completeTotalIssues.value = arg.totalIssuesFound;
    loadIssues();
    loadOrphanDirectories();
  },
});

const startCheck = async () => {
  startChecking();
  checkComplete.value = false;
  checkIssuesFound.value = 0;
  checkMessage.value = "";
  issues.value = [];
  await ConsistencyService.startCheck();
};

const loadIssues = async () => {
  issues.value = await ConsistencyService.getIssues();
};

const loadOrphanDirectories = async () => {
  orphanDirectories.value = await ConsistencyService.getOrphanDirectories();
};

const getBulkResolveDescription = (issueType: string): string => {
  switch (issueType) {
    case "WrongFilePath":
      return "Each audiobook file will be moved to its correct location based on library metadata.";
    case "MissingDescTxt":
    case "IncorrectDescTxt":
      return "A desc.txt sidecar file containing the book description will be created or updated for each affected book.";
    case "MissingReaderTxt":
    case "IncorrectReaderTxt":
      return "A reader.txt sidecar file containing narrator information will be created or updated for each affected book.";
    case "MissingCoverFile":
      return "The cover image will be extracted from each affected audiobook file.";
    case "TagMismatch":
      return "Each audiobook file's m4b tags will be rewritten to match the library metadata (author, series, series part, year, etc.), and the file relocated if that changes its path.";
    default:
      return "Continue?";
  }
};

const getIssueIcon = (issueType: string): string => {
  switch (issueType) {
    case "MissingMediaFile":
      return "mdi-file-remove";
    case "WrongFilePath":
      return "mdi-swap-horizontal";
    case "MissingDescTxt":
    case "IncorrectDescTxt":
    case "MissingReaderTxt":
    case "IncorrectReaderTxt":
      return "mdi-text-box-remove";
    case "MissingCoverFile":
      return "mdi-image-remove";
    case "TagMismatch":
      return "mdi-tag-off";
    default:
      return "mdi-alert";
  }
};

const onResolveClick = (issue: ConsistencyIssue) => {
  if (issue.issueType === "MissingMediaFile") {
    pendingResolveIssue.value = issue;
    pendingBulkType.value = null;
    confirmDialog.value = true;
  } else {
    resolveIssue(issue);
  }
};

const onBulkResolveClick = (issueType: string) => {
  const group = groupedByType.value.find((g) => g.issueType === issueType);
  if (!group) return;

  pendingBulkType.value = issueType;
  pendingBulkCount.value = group.issues.length;
  pendingResolveIssue.value = null;
  pendingSelectedType.value = null;
  pendingSelectedIssueIds.value = [];
  confirmDialog.value = true;
};

const selectedCountInGroup = (group: TypeGroup): number =>
  group.issues.filter((i) => selectedIssueIds.value.has(i.id)).length;

const isGroupFullySelected = (group: TypeGroup): boolean =>
  group.visibleIssues.length > 0 &&
  group.visibleIssues.every((i) => selectedIssueIds.value.has(i.id));

const isGroupPartiallySelected = (group: TypeGroup): boolean =>
  !isGroupFullySelected(group) &&
  group.visibleIssues.some((i) => selectedIssueIds.value.has(i.id));

const toggleIssueSelected = (issueId: number) => {
  if (selectedIssueIds.value.has(issueId)) {
    selectedIssueIds.value.delete(issueId);
  } else {
    selectedIssueIds.value.add(issueId);
  }
};

const toggleSelectAllVisible = (group: TypeGroup) => {
  if (isGroupFullySelected(group)) {
    for (const issue of group.visibleIssues) {
      selectedIssueIds.value.delete(issue.id);
    }
  } else {
    for (const issue of group.visibleIssues) {
      selectedIssueIds.value.add(issue.id);
    }
  }
};

const onResolveSelectedClick = (group: TypeGroup) => {
  const ids = group.issues
    .filter((i) => selectedIssueIds.value.has(i.id))
    .map((i) => i.id);
  if (ids.length === 0) return;

  pendingSelectedType.value = group.issueType;
  pendingSelectedIssueIds.value = ids;
  pendingBulkType.value = null;
  pendingResolveIssue.value = null;
  confirmDialog.value = true;
};

const cancelConfirm = () => {
  confirmDialog.value = false;
  pendingResolveIssue.value = null;
  pendingBulkType.value = null;
  pendingSelectedType.value = null;
  pendingSelectedIssueIds.value = [];
};

const confirmResolve = () => {
  if (pendingSelectedType.value && pendingSelectedIssueIds.value.length > 0) {
    resolveSelected(pendingSelectedType.value, pendingSelectedIssueIds.value);
  } else if (pendingBulkType.value) {
    bulkResolve(pendingBulkType.value);
  } else if (pendingResolveIssue.value) {
    resolveIssue(pendingResolveIssue.value);
  }
  confirmDialog.value = false;
  pendingResolveIssue.value = null;
  pendingBulkType.value = null;
  pendingSelectedType.value = null;
  pendingSelectedIssueIds.value = [];
};

const resolveSelected = async (issueType: string, ids: number[]) => {
  resolvingSelectedTypes.value.add(issueType);
  try {
    const result = await ConsistencyService.resolveSelectedIssues(ids);
    for (const id of ids) {
      selectedIssueIds.value.delete(id);
    }
    let msg = `Resolved ${result.resolved} issues`;
    if (result.failed > 0) {
      msg += ` (${result.failed} failed)`;
    }
    snackbarText.value = msg;
    snackbar.value = true;
  } catch {
    snackbarText.value = "Failed to resolve selected issues";
    snackbar.value = true;
  } finally {
    resolvingSelectedTypes.value.delete(issueType);
    await loadIssues();
  }
};

const bulkResolve = async (issueType: string) => {
  resolvingTypes.value.add(issueType);
  try {
    const result = await ConsistencyService.resolveByType(issueType);
    issues.value = issues.value.filter((i) => {
      if (issueType === "MissingMediaFile" || issueType === "WrongFilePath") {
        const resolvedAudiobookIds = new Set(
          issues.value
            .filter((x) => x.issueType === issueType)
            .map((x) => x.audiobookId),
        );
        return !resolvedAudiobookIds.has(i.audiobookId);
      }
      if (
        issueType === "MissingDescTxt" ||
        issueType === "IncorrectDescTxt" ||
        issueType === "MissingReaderTxt" ||
        issueType === "IncorrectReaderTxt"
      ) {
        const metadataTypes = [
          "MissingDescTxt",
          "IncorrectDescTxt",
          "MissingReaderTxt",
          "IncorrectReaderTxt",
        ];
        const resolvedAudiobookIds = new Set(
          issues.value
            .filter((x) => x.issueType === issueType)
            .map((x) => x.audiobookId),
        );
        if (resolvedAudiobookIds.has(i.audiobookId)) {
          return !metadataTypes.includes(i.issueType);
        }
        return true;
      }
      return i.issueType !== issueType;
    });
    let msg = `Resolved ${result.resolved} issues`;
    if (result.failed > 0) {
      msg += ` (${result.failed} failed)`;
    }
    snackbarText.value = msg;
    snackbar.value = true;
  } catch {
    snackbarText.value = "Failed to bulk resolve issues";
    snackbar.value = true;
  } finally {
    resolvingTypes.value.delete(issueType);
  }
};

const resolveIssue = async (issue: ConsistencyIssue) => {
  resolvingIds.value.add(issue.id);
  try {
    await ConsistencyService.resolveIssue(issue.id);
    issues.value = issues.value.filter((i) => {
      if (
        issue.issueType === "MissingMediaFile" ||
        issue.issueType === "WrongFilePath"
      ) {
        return i.audiobookId !== issue.audiobookId;
      }
      if (
        issue.issueType === "MissingDescTxt" ||
        issue.issueType === "IncorrectDescTxt" ||
        issue.issueType === "MissingReaderTxt" ||
        issue.issueType === "IncorrectReaderTxt"
      ) {
        return !(
          i.audiobookId === issue.audiobookId &&
          (i.issueType === "MissingDescTxt" ||
            i.issueType === "IncorrectDescTxt" ||
            i.issueType === "MissingReaderTxt" ||
            i.issueType === "IncorrectReaderTxt")
        );
      }
      return i.id !== issue.id;
    });
    snackbarText.value = "Issue resolved successfully";
    snackbar.value = true;
  } catch {
    snackbarText.value = "Failed to resolve issue";
    snackbar.value = true;
  } finally {
    resolvingIds.value.delete(issue.id);
  }
};

const onResolveOrphanClick = (dir: OrphanDirectory) => {
  pendingOrphanDirectory.value = dir;
  pendingOrphanBulk.value = false;
  orphanConfirmDialog.value = true;
};

const onBulkResolveOrphansClick = () => {
  pendingOrphanDirectory.value = null;
  pendingOrphanBulk.value = true;
  orphanConfirmDialog.value = true;
};

const cancelOrphanConfirm = () => {
  orphanConfirmDialog.value = false;
  pendingOrphanDirectory.value = null;
  pendingOrphanBulk.value = false;
};

const confirmOrphanResolve = () => {
  if (pendingOrphanBulk.value) {
    bulkResolveOrphans();
  } else if (pendingOrphanDirectory.value) {
    resolveOrphanDirectory(pendingOrphanDirectory.value);
  }
  orphanConfirmDialog.value = false;
  pendingOrphanDirectory.value = null;
  pendingOrphanBulk.value = false;
};

const resolveOrphanDirectory = async (dir: OrphanDirectory) => {
  resolvingOrphanIds.value.add(dir.id);
  try {
    await ConsistencyService.resolveOrphanDirectory(dir.id);
    orphanDirectories.value = orphanDirectories.value.filter(
      (d) => d.id !== dir.id,
    );
    snackbarText.value = "Directory deleted successfully";
    snackbar.value = true;
  } catch {
    snackbarText.value = "Failed to delete directory";
    snackbar.value = true;
  } finally {
    resolvingOrphanIds.value.delete(dir.id);
  }
};

const bulkResolveOrphans = async () => {
  resolvingAllOrphans.value = true;
  try {
    const result = await ConsistencyService.resolveAllOrphanDirectories();
    let msg = `Deleted ${result.resolved} directories`;
    if (result.failed > 0) {
      msg += ` (${result.failed} failed)`;
    }
    snackbarText.value = msg;
    snackbar.value = true;
  } catch {
    snackbarText.value = "Failed to bulk delete orphaned directories";
    snackbar.value = true;
  } finally {
    resolvingAllOrphans.value = false;
    await loadOrphanDirectories();
  }
};

onMounted(() => {
  loadIssues();
  loadOrphanDirectories();
});
</script>

<style scoped>
.issue-subtitle {
  white-space: normal !important;
  -webkit-line-clamp: unset !important;
  overflow: visible !important;
}

.issue-item :deep(.v-list-item-subtitle) {
  white-space: normal !important;
  -webkit-line-clamp: unset !important;
  overflow: visible !important;
}
</style>

// client/src/components/LibraryConsistency.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  ShieldAlert,
  Play,
  CheckCircle2,
  AlertTriangle,
  FolderX,
  Loader2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { OperationProgressBar } from "./OperationProgressBar";
import { DiffDisplay } from "./DiffDisplay";
import { consistencyApi } from "@/services/api";
import { useSignalREvent } from "@/hooks/useSignalR";
import { handleApiError } from "@/lib/api";
import { toast } from "sonner";
import type { ConsistencyIssue } from "@/types/ConsistencyIssue";
import type { OrphanDirectory } from "@/types/OrphanDirectory";

interface ProgressPayload {
  message: string;
  booksChecked: number;
  totalBooks: number;
  issuesFound: number;
}

interface CompletePayload {
  totalBooksChecked: number;
  totalIssuesFound: number;
}

export function LibraryConsistency() {
  const queryClient = useQueryClient();

  // Check state
  const [checking, setChecking] = useState(false);
  const [checkProgress, setCheckProgress] = useState<ProgressPayload | null>(null);
  const [checkCompleteResult, setCheckCompleteResult] = useState<CompletePayload | null>(null);

  // Selection state
  const [selectedIssueIds, setSelectedIssueIds] = useState<Set<number>>(new Set());
  const [resolvingIds, setResolvingIds] = useState<Set<number>>(new Set());
  const [resolvingTypes, setResolvingTypes] = useState<Set<string>>(new Set());
  const [resolvingSelected, setResolvingSelected] = useState(false);

  // Orphan dialog state
  const [orphanToDelete, setOrphanToDelete] = useState<OrphanDirectory | null>(null);
  const [deleteAllOrphansOpen, setDeleteAllOrphansOpen] = useState(false);
  const [deletingOrphan, setDeletingOrphan] = useState(false);

  const { data, isLoading: loading } = useQuery({
    queryKey: ["consistency"],
    queryFn: async () => {
      const [issuesData, orphansData] = await Promise.all([
        consistencyApi.getIssues(),
        consistencyApi.getOrphanDirectories().catch(() => []),
      ]);
      return { issues: issuesData, orphanDirs: orphansData };
    },
  });

  const issues = data?.issues ?? [];
  const orphanDirs = data?.orphanDirs ?? [];

  useSignalREvent<ProgressPayload>("ConsistencyCheckProgress", (data) => {
    setChecking(true);
    setCheckProgress(data);
  });

  useSignalREvent<CompletePayload>("ConsistencyCheckComplete", (data) => {
    setChecking(false);
    setCheckProgress(null);
    setCheckCompleteResult(data);
    toast.success(
      `Check complete: ${data.totalBooksChecked} books checked, ${data.totalIssuesFound} issues found`,
    );
    void queryClient.invalidateQueries({ queryKey: ["consistency"] });
  });

  const handleStartCheck = async () => {
    setChecking(true);
    setCheckCompleteResult(null);
    try {
      await consistencyApi.startCheck();
      toast.success("Consistency check started in background");
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
      setChecking(false);
    }
  };

  const handleResolveSingle = async (issue: ConsistencyIssue) => {
    setResolvingIds((prev) => new Set(prev).add(issue.id));
    try {
      await consistencyApi.resolveIssue(issue.id);
      toast.success("Issue resolved");
      void queryClient.invalidateQueries({ queryKey: ["consistency"] });
      setSelectedIssueIds((prev) => {
        const next = new Set(prev);
        next.delete(issue.id);
        return next;
      });
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setResolvingIds((prev) => {
        const next = new Set(prev);
        next.delete(issue.id);
        return next;
      });
    }
  };

  const handleResolveSelected = async (issueIds: number[]) => {
    if (issueIds.length === 0) return;
    setResolvingSelected(true);
    try {
      const res = await consistencyApi.resolveSelected(issueIds);
      toast.success(`Resolved ${res.resolved} issues (${res.failed} failed)`);
      void queryClient.invalidateQueries({ queryKey: ["consistency"] });
      setSelectedIssueIds(new Set());
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setResolvingSelected(false);
    }
  };

  const handleResolveByType = async (issueType: string) => {
    setResolvingTypes((prev) => new Set(prev).add(issueType));
    try {
      const res = await consistencyApi.resolveByType(issueType);
      toast.success(`Resolved ${res.resolved} issues of type "${issueType}"`);
      void queryClient.invalidateQueries({ queryKey: ["consistency"] });
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setResolvingTypes((prev) => {
        const next = new Set(prev);
        next.delete(issueType);
        return next;
      });
    }
  };

  const handleDeleteOrphan = async () => {
    if (!orphanToDelete) return;
    setDeletingOrphan(true);
    try {
      await consistencyApi.resolveOrphanDirectory(orphanToDelete.id);
      toast.success("Orphaned directory removed");
      void queryClient.invalidateQueries({ queryKey: ["consistency"] });
      setOrphanToDelete(null);
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setDeletingOrphan(false);
    }
  };

  const handleDeleteAllOrphans = async () => {
    setDeletingOrphan(true);
    try {
      const res = await consistencyApi.resolveAllOrphanDirectories();
      toast.success(`Deleted ${res.resolved} orphaned directories`);
      void queryClient.invalidateQueries({ queryKey: ["consistency"] });
      setDeleteAllOrphansOpen(false);
    } catch (err: unknown) {
      toast.error(handleApiError(err).message);
    } finally {
      setDeletingOrphan(false);
    }
  };

  // Group issues by issueType
  const groupedIssues = issues.reduce<Record<string, ConsistencyIssue[]>>((acc, issue) => {
    const list = acc[issue.issueType] || [];
    list.push(issue);
    acc[issue.issueType] = list;
    return acc;
  }, {});

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <Button variant="ghost" size="sm" asChild>
          <Link to="/library">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Library
          </Link>
        </Button>

        <Button
          variant="default"
          onClick={() => {
            void handleStartCheck();
          }}
          disabled={checking}
        >
          <Play className={`mr-2 h-4 w-4 ${checking ? "animate-spin" : ""}`} />
          {checking ? "Running Check..." : "Run Consistency Check"}
        </Button>
      </div>

      <div>
        <h1 className="text-foreground flex items-center gap-2 text-2xl font-bold">
          <ShieldAlert className="text-primary h-6 w-6" />
          Library Consistency
        </h1>
        <p className="text-muted-foreground text-sm">
          Verifies that every book in the library has the correct file path, sidecar metadata files
          (desc.txt, reader.txt), and a cover image, and detects leftover orphaned folders.
        </p>
      </div>

      {checking && checkProgress && (
        <OperationProgressBar
          processed={checkProgress.booksChecked}
          total={checkProgress.totalBooks}
          label={`${checkProgress.message || "Checking consistency..."} (${checkProgress.issuesFound} issues found)`}
        />
      )}

      {checkCompleteResult && (
        <div className="border-primary/20 bg-primary/10 text-foreground rounded-lg border p-3 text-xs">
          Check complete: {checkCompleteResult.totalBooksChecked} books checked,{" "}
          {checkCompleteResult.totalIssuesFound} issues found.
        </div>
      )}

      <div className="space-y-6">
        <div>
          <h2 className="text-foreground text-lg font-bold">Issues ({issues.length})</h2>

          {loading ? (
            <div className="text-muted-foreground flex items-center justify-center py-12">
              <Loader2 className="text-primary mr-2 h-6 w-6 animate-spin" />
              <span className="text-sm">Checking issues...</span>
            </div>
          ) : issues.length === 0 ? (
            <Card className="mt-3 p-8 text-center">
              <CheckCircle2 className="mx-auto mb-2 h-10 w-10 text-emerald-500" />
              <h3 className="text-foreground text-base font-semibold">
                No Consistency Issues Found
              </h3>
              <p className="text-muted-foreground mt-1 text-xs">
                All files, tags, and sidecar assets match their expected state.
              </p>
            </Card>
          ) : (
            <Accordion type="multiple" className="mt-3 space-y-3">
              {Object.entries(groupedIssues).map(([type, typeIssues]) => {
                const isResolvingType = resolvingTypes.has(type);
                const selectedInGroup = typeIssues.filter((i) => selectedIssueIds.has(i.id));

                return (
                  <AccordionItem
                    key={type}
                    value={type}
                    className="border-border bg-card rounded-lg border px-4 shadow-sm"
                  >
                    <AccordionTrigger className="py-3 hover:no-underline">
                      <div className="flex w-full items-center justify-between pr-4 text-left">
                        <div className="flex items-center gap-2">
                          <AlertTriangle className="h-4 w-4 text-amber-500" />
                          <span className="text-foreground font-semibold">{type}</span>
                        </div>
                        <Badge
                          variant="secondary"
                          className="bg-amber-500/15 text-amber-600 dark:text-amber-400"
                        >
                          {typeIssues.length}
                        </Badge>
                      </div>
                    </AccordionTrigger>

                    <AccordionContent className="border-border border-t pt-4 pb-4">
                      <div className="space-y-4">
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <div className="flex items-center gap-2">
                            <input
                              type="checkbox"
                              checked={
                                selectedInGroup.length === typeIssues.length &&
                                typeIssues.length > 0
                              }
                              onChange={(e) => {
                                const check = e.target.checked;
                                setSelectedIssueIds((prev) => {
                                  const next = new Set(prev);
                                  for (const i of typeIssues) {
                                    if (check) next.add(i.id);
                                    else next.delete(i.id);
                                  }
                                  return next;
                                });
                              }}
                              className="border-border h-4 w-4 rounded"
                            />
                            <span className="text-muted-foreground text-xs">
                              Select all visible ({selectedInGroup.length} selected)
                            </span>
                          </div>

                          <div className="flex items-center gap-2">
                            {selectedInGroup.length > 0 && (
                              <Button
                                size="sm"
                                variant="outline"
                                disabled={resolvingSelected}
                                onClick={() => {
                                  void handleResolveSelected(selectedInGroup.map((i) => i.id));
                                }}
                              >
                                Resolve Selected ({selectedInGroup.length})
                              </Button>
                            )}

                            <Button
                              size="sm"
                              variant="secondary"
                              disabled={isResolvingType}
                              onClick={() => {
                                void handleResolveByType(type);
                              }}
                            >
                              {isResolvingType ? (
                                <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                              ) : null}
                              Resolve All {typeIssues.length}
                            </Button>
                          </div>
                        </div>

                        <div className="space-y-2">
                          {typeIssues.map((issue) => {
                            const isResolving = resolvingIds.has(issue.id);
                            const isChecked = selectedIssueIds.has(issue.id);

                            return (
                              <div
                                key={issue.id}
                                className="border-border bg-muted/30 flex flex-col gap-2 rounded-md border p-3 sm:flex-row sm:items-center sm:justify-between"
                              >
                                <div className="flex min-w-0 items-start gap-3">
                                  <input
                                    type="checkbox"
                                    checked={isChecked}
                                    onChange={(e) => {
                                      const checked = e.target.checked;
                                      setSelectedIssueIds((prev) => {
                                        const next = new Set(prev);
                                        if (checked) next.add(issue.id);
                                        else next.delete(issue.id);
                                        return next;
                                      });
                                    }}
                                    className="border-border mt-1 h-4 w-4 rounded"
                                  />

                                  <div className="min-w-0 space-y-1">
                                    <Link
                                      to={`/library/book/${issue.audiobookId}`}
                                      className="text-primary text-xs font-semibold hover:underline"
                                    >
                                      {issue.authors.join(", ")} &mdash; {issue.bookName}
                                    </Link>
                                    <p className="text-muted-foreground text-xs">
                                      {issue.description}
                                    </p>

                                    {issue.expectedValue && issue.actualValue ? (
                                      <DiffDisplay
                                        expected={issue.expectedValue}
                                        actual={issue.actualValue}
                                      />
                                    ) : issue.expectedValue ? (
                                      <div className="text-muted-foreground text-[11px]">
                                        Expected: {issue.expectedValue}
                                      </div>
                                    ) : null}
                                  </div>
                                </div>

                                <Button
                                  size="sm"
                                  variant="outline"
                                  disabled={isResolving}
                                  onClick={() => {
                                    void handleResolveSingle(issue);
                                  }}
                                  className="shrink-0 self-end sm:self-center"
                                >
                                  {isResolving ? (
                                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                                  ) : (
                                    "Resolve"
                                  )}
                                </Button>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                );
              })}
            </Accordion>
          )}
        </div>

        {orphanDirs.length > 0 && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-foreground flex items-center gap-2 text-lg font-bold">
                <FolderX className="h-5 w-5 text-amber-500" />
                Orphaned Directories ({orphanDirs.length})
              </h2>
              <Button variant="destructive" size="sm" onClick={() => setDeleteAllOrphansOpen(true)}>
                Delete All {orphanDirs.length}
              </Button>
            </div>

            <div className="space-y-2">
              {orphanDirs.map((dir) => (
                <div
                  key={dir.id}
                  className="border-border bg-card flex items-center justify-between rounded-lg border p-3"
                >
                  <span className="text-muted-foreground font-mono text-xs break-all">
                    {dir.directoryPath}
                  </span>
                  <Button variant="outline" size="sm" onClick={() => setOrphanToDelete(dir)}>
                    Delete
                  </Button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <Dialog
        open={Boolean(orphanToDelete)}
        onOpenChange={(open) => {
          if (!open) setOrphanToDelete(null);
        }}
      >
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Delete Orphaned Directory</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <p className="text-muted-foreground text-xs">
              Are you sure you want to permanently delete this empty or orphaned folder?
            </p>
            <div className="bg-muted rounded p-2 font-mono text-xs break-all">
              {orphanToDelete?.directoryPath}
            </div>
            <div className="border-border flex justify-end gap-2 border-t pt-4">
              <Button variant="outline" onClick={() => setOrphanToDelete(null)}>
                Cancel
              </Button>
              <Button
                variant="destructive"
                disabled={deletingOrphan}
                onClick={() => {
                  void handleDeleteOrphan();
                }}
              >
                {deletingOrphan ? "Deleting..." : "Delete Permanently"}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={deleteAllOrphansOpen} onOpenChange={setDeleteAllOrphansOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Delete All Orphaned Directories</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <p className="text-muted-foreground text-xs">
              This will permanently delete <strong>all {orphanDirs.length}</strong> orphaned
              directories and any leftover files in them.
            </p>
            <div className="border-border flex justify-end gap-2 border-t pt-4">
              <Button variant="outline" onClick={() => setDeleteAllOrphansOpen(false)}>
                Cancel
              </Button>
              <Button
                variant="destructive"
                disabled={deletingOrphan}
                onClick={() => {
                  void handleDeleteAllOrphans();
                }}
              >
                {deletingOrphan ? "Deleting..." : "Delete All"}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default LibraryConsistency;
